eng/Version.Details.xml
eng/Versions.props
global.json
samples/ReverseProxy.Sample/ReverseProxy.Sample.csproj
samples/SampleClient/SampleClient.csproj
samples/SampleServer/SampleServer.csproj
src/ReverseProxy.Common/Microsoft.ReverseProxy.Common.csproj
src/ReverseProxy.Core/Microsoft.ReverseProxy.Core.csproj
src/ReverseProxy.Signals/Microsoft.ReverseProxy.Signals.csproj
src/ReverseProxy.Utilities/Microsoft.ReverseProxy.Utilities.csproj
test/ReverseProxy.Common.Tests/Microsoft.ReverseProxy.Common.Tests.csproj
test/ReverseProxy.Core.Tests/Microsoft.ReverseProxy.Core.Tests.csproj
test/ReverseProxy.Signals.Tests/Microsoft.ReverseProxy.Signals.Tests.csproj
test/ReverseProxy.Utilities.Tests/Microsoft.ReverseProxy.Utilities.Tests.csproj
test/Tests.Common/Tests.Common.csproj

Fixes #27 
I added `Microsoft.NETCore.App` as a Darc-tracked dependency and then did a manual `darc update-dependencies` to get the latest .NET 5 build in. Then I updated all the TFMs. Everything seems to be working and using .NET 5!
Once this is in, I can update darc to bring in new builds at whatever cadence we want. The trade off there is that more frequent updates means we have the latest and greatest, at the cost of more dependency update PRs. The dependency update PRs *should* auto-merge, but we may have to watch out for breaking changes. Also, more updates means more commits that are just "update dependencies" :).
TODO at merge:

manually update dependencies to .NET 5

---

README.md

Unless the project does not work in F#.

Remove C#-specific reference

---

src/ReverseProxy.Core/Abstractions/BackendDiscovery/Contract/LoadBalancingMode.cs
src/ReverseProxy.Core/Middleware/LoadBalancingMiddleware.cs
src/ReverseProxy.Core/Service/Proxy/LoadBalancer.cs
src/ReverseProxy.Core/Service/RuntimeModel/BackendConfig.cs
src/ReverseProxy.Core/Util/AtomicCounter.cs
test/ReverseProxy.Core.Tests/Middleware/LoadBalancerMiddlewareTests.cs
test/ReverseProxy.Core.Tests/Service/Proxy/LoadBalancerTests.cs

#72 While we debated more complex backend data storage mechanisms, I wanted to try something simple first. Built in algorithms can avail themselves of built in structures so I added the round robin state tracker to the existing BackendLoadBalancingOptions structure.

Round robin load balancing 

---

eng/Signing.props

Signing validation in our internal builds is failing because this file is missing. As far as I can tell, the content is optional but the load is happening unconditionally (I think that's fixed in the latest Arcade).
I'm going to merge this quickly so I can get it in to the internal branch and make sure it unblocks the build.

workaround arcade signing issue

---

docs/operations/BranchingAndRelease.md

Added docs on how to manage branching for releases. The flow described here is what we've previously discussed
* .NET 5 snaps their release branch, and at that time we change our `master` to pull from that release branch
* We continue open development in `master`, but won't get new .NET 5 builds
* At some point prior to release, we branch `release/1.0.0-previewX` and move `master` on to the next preview.
An alternate plan is to just branch when .NET branches. It might make things smoother. I'd be happy to write up the docs for that strategy if it seems like it would be easier. We'd still be able to decide for ourselves when to stop coding, but we might have to switch PRs between branches more.
Thoughts?

add docs for branching for release

---

README.md

I'd also like to add a link in the repo description header, but I think you need to be a repo admin to edit that. Andrew?

Add a link to the docs from the readme

---

docs/operations/Branching.md
docs/operations/README.md
docs/operations/Release.md

Adds a doc on how to release packages. Also reorganized the `docs/operations/` folder a bit to have a README, and added a quick note on updating branding during branching.

add release docs

---

samples/ReverseProxy.Sample/CustomConfigFilter.cs
samples/ReverseProxy.Sample/ReverseProxy.Sample.csproj
src/ReverseProxy.Core/Abstractions/BackendDiscovery/Contract/Backend.cs
src/ReverseProxy.Core/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
src/ReverseProxy.Core/Service/Config/ConfigErrors.cs
src/ReverseProxy.Core/Service/Config/DynamicConfigBuilder.cs
src/ReverseProxy.Core/Service/Config/IProxyConfigFilter.cs
test/ReverseProxy.Core.Tests/Service/Config/DynamicConfigBuilderTests.cs

This finishes off the feedback from #9 about inconsistencies between ProxyRoute having an Id and Backend not due to differences in the config structure.
The new field needs to be populated after config binding.

Add Id to Backend type 

---

global.json
samples/BenchmarkApp/BenchmarkApp.csproj
samples/ReverseProxy.Sample/ReverseProxy.Sample.csproj
src/ReverseProxy/Microsoft.ReverseProxy.csproj
src/ReverseProxy/Service/Proxy/HttpProxy.cs
src/ReverseProxy/Utilities/ProtocolHelper.cs
test/ReverseProxy.Tests/Microsoft.ReverseProxy.Tests.csproj

#159 We were calling one new 5.0 API, Microsoft.AspNetCore.Http.HttpProtocol.IsHttp2. We don't strictly need it, but it does make a good example for how to #if around differences.

Cross target .NET 5.0 and 3.1

---

.github/workflows/docfx_build.yml

Use the github-actions "bot" account as the author for the commit made to update the docs. Currently it uses the user who triggered the action (i.e. the committer of the PR that was merged in to master), but the GitHub Action is the one actually creating the content so this seems clearer
I borrowed this technique from https://github.com/peter-evans/create-pull-request/blob/25902ccdd12cde734aa20ca940ee41c07f33e906/src/cpr/create_pull_request.py#L17
After merging, I'll keep an eye on https://github.com/microsoft/reverse-proxy/actions to double check that it worked out.

Change gh-pages commit author

---

docs/docfx/articles/getting_started.md

I though it was saying that `"app1" needs to be defined as the value "route2"`

[Getting Started] Clarifying word usage

---

src/ReverseProxy/Service/Proxy/LoadBalancer.cs

Addressing (#198)
This preserves ordering when `offest` is negative. Using Math.Abs would reverse the ordering when `offset` is negative.
There is a discontinuity when `offset` transitions from positive to negative. This should be acceptable "unfairness" over 2B requests.
For example with `endpoints.Count` of 5:
```
offset		computed index
2147483640	0
2147483641	1
2147483642	2
2147483643	3
2147483644	4
2147483645	0
2147483646	1
2147483647	2
-2147483648	0
-2147483647	1
-2147483646	2
-2147483645	3
-2147483644	4
```

Preventing negative indexes

---

src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs
src/ReverseProxy/Service/HealthProbe/BackendProberFactory.cs
test/ReverseProxy.Tests/Service/HealthProbe/BackendProberFactoryTests.cs

closes #186 
Saw this one show up in my email and figured it was an easy fix. Migrated the initialization to use a RandomFactory and then grab a new instance of System.Random from there.

Moved to use of IRandomFactory in ProxyInvokerMiddleware

---

src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
src/ReverseProxy/Service/RuntimeModel/DestinationInfo.cs
test/ReverseProxy.Tests/Service/Proxy/LoadBalancerTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/BackendInfoTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/DestinationInfoTests.cs

https://github.com/microsoft/reverse-proxy/pull/174#discussion_r429327553

Reduce Allocation when choosing the Destination

---

docs/docfx/articles/getting_started.md
global.json
samples/BenchmarkApp/BenchmarkApp.csproj
samples/ReverseProxy.Sample/ReverseProxy.Sample.csproj
samples/SampleClient/SampleClient.csproj
samples/SampleServer/SampleServer.csproj
src/ReverseProxy/Microsoft.ReverseProxy.csproj
test/ReverseProxy.Tests/Microsoft.ReverseProxy.Tests.csproj

TFM set to `.net5.0` in all project. Additionally, `rollForward` is enabled and set to `latestMinor`
**Note.** `dotnet new` does **not** support `.net5.0` TFM, yet.
Fixes #189

TargetFramework set to .net5.0

---

src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
test/ReverseProxy.Tests/Service/Config/DynamicConfigBuilderTests.cs

Follow up to #265, I missed a DI dependency. Your average app will already have this from AddControllers, or if they configure AuthZ themselves, but a basic app might not have this dependency. The libraries no-op if they're not used, so adding it is harmless.
```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.ReverseProxy.Service.IDynamicConfigBuilder Lifetime: Singleton ImplementationType: Microsoft.ReverseProxy.Service.DynamicConfigBuilder': Unable to resolve service for type 'Microsoft.AspNetCore.Authorization.IAuthorizationPolicyProvider' while attempting to activate 'Microsoft.ReverseProxy.Service.RouteValidator'.) (Error while validating the service descriptor …
```

AddAuthorization DI dependency

---

src/ReverseProxy/Service/RuntimeModel/Transforms/PathRouteValuesTransform.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/PathRouteValuesTransformTests.cs

#268 (Preview2 feedback)
The way we used the binder before it would append unused route parameters to the path as a query string.
A) We don't want the unused parameters.
B) That query string was being encoded inside the path.
@javiercn

Drop unused paramters from PathPattern 

---

README.md
docs/DailyBuilds.md

We've started publishing daily builds to a feed so this adds instructions for accessing them. They're copied wholesale from [AspNetCore](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md).
I'm also updating the readme to recommend previews and daily builds.
Fixes #271

Add instructions for using daily builds

---

docs/docfx/articles/authn-authz.md
docs/docfx/articles/getting_started.md
docs/docfx/articles/transforms.md
samples/ReverseProxy.Sample/appsettings.json
src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
src/ReverseProxy/Service/Config/DynamicConfigBuilder.cs
src/ReverseProxy/Service/Config/RuleParsing/RouteValidator.cs
src/ReverseProxy/Service/ConfigModel/ParsedRoute.cs
src/ReverseProxy/Service/DynamicEndpoints/RuntimeRouteBuilder.cs
test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs
test/ReverseProxy.Tests/Service/Config/DynamicConfigBuilderTests.cs
test/ReverseProxy.Tests/Service/Config/RuleParsing/RouteValidatorTests.cs
test/ReverseProxy.Tests/Service/DynamicEndpoints/RuntimeRouteBuilderTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/206

Support Multiple Hosts for a Route

---

src/ReverseProxy/Middleware/AffinitizeRequestMiddleware.cs
src/ReverseProxy/Middleware/AffinitizedDestinationLookupMiddleware.cs
src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
test/ReverseProxy.Tests/Middleware/AffinitizeRequestMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/AffinitizedDestinationLookupMiddlewareTests.cs

- The operation logger isn't a profiler API and should only be used for non trivial work (like proxying the request to the destination).

Remove trivial uses of operation logging

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs
src/ReverseProxy/Service/Proxy/Infrastructure/IProxyHttpClientFactory.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs
test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs
test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs

Contributes to #137. We still need to finish the design around the client factory but this part was well understood. The separate handler with its own config is not needed for WebSocket/Upgrade scenarios. The pooling setting was an optimization copied from ClientWebSocket. 
I need to do some refactoring in HttpProxy and it will be easier if I get this out of the way first.

Remove CreateUpgradableClient from the client factory 

---

samples/SampleServer/Controllers/HttpController.cs
src/ReverseProxy/Service/Proxy/HttpProxy.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs
test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs

This is a temporary mitigation for #255. IIS marks all requests as upgradable, and we don't proxy the request body for upgradable requests, so that breaks all POST requests in IIS.
Mitigation: Constrain upgrades to WebSocket requests. In theory Upgrade can be used for other things but we haven't seen that in practice.
We've had at least three separate reports of this now, so I want to get this mitigation into preview3.

Mitigate POST issue in IIS 

---

samples/BenchmarkApp/Startup.cs

@sebastienros This should fix the issues you were seeing. Now, instead of the requiring the Host header from the load test client match the BenchmarkApp's --urls parameter, the BenchmarkApp should proxy any request.

Use catchall route in BenchmarkApp

---

azure-pipelines.yml

Follow-up, it keeps trying to publish symbols from the linux build which we don't care about. This changes it to match the mac build.

Disable official builds for linux

---

src/ReverseProxy/Service/Config/TransformBuilder.cs
test/ReverseProxy.Tests/Service/Config/ProxyRouteTransformExtensionsTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/345

Pass PathString.Value to prevent encoding

---

docs/docfx/articles/toc.yml

The https://microsoft.github.io/reverse-proxy/articles/ TOC was missing a few entries. Turns out it was an issue with the yaml.

Fix articles TOC

---

docs/docfx/articles/authn-authz.md

```
error CS1061: 'IList<IAuthorizationRequirement>' does not contain a definition for 'RequireAuthenticatedUser' and no accessible extension method 'RequireAuthenticatedUser' accepting a first argument of type 'IList<IAuthorizationRequirement>' could be found (are you missing a using directive or an assembly reference?)
```

Fix policy configuration example.

---

.github/workflows/docfx_build.yml
docs/docfx/readme.md

Fixes #344 Our docs live in the repo and get updated live with commits to master. However, when we make breaking changes the published docs get out of sync with the last release (e.g. preview4) causing confusion for some users.
I've changed the doc publishing process to explicitly track a release/docs branch. See the updated readme.

Change the doc publishing to track a release branch

---

azure-pipelines.yml
global.json

Fixes #377 - Dlls get a bunch of new metadata from the compiler
Unblocks #330 @Kahbazi - I think there was a bug in the preview 6 SDK about the Pipes library on 3.1. Can you rebase after this is merged and try again?
Blocked: We need the CI agents to be updated to VS 16.8.0 Preview 2 to unblock the build.

Move to the preview.8 SDK

---

azure-pipelines.yml

These two steps were broken when we moved to the preview8 SDK because the machines that run the post-build validation don't have the new version of VS yet. I'll file an issue to re-enable.

Disable broken validation steps

---

.config/CredScanSuppressions.json
test/ReverseProxy.Tests/Configuration/CertificateConfigLoaderTests.cs
test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs

Use config-based suppressions for all passwords in the flagged `.cs` files.

Update CredScan suppressions

---

docs/docfx/articles/configproviders.md
docs/docfx/articles/getting_started.md

Probably should have double checked the spelling before merging #436 instead of immediately after 😆

programatically -> programmatically

---

docs/docfx/articles/transforms.md
src/ReverseProxy/Service/Config/ProxyRouteTransformExtensions.cs
src/ReverseProxy/Service/Config/TransformBuilder.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/HttpMethodTransform.cs
test/ReverseProxy.Tests/Service/Config/ProxyRouteTransformExtensionsTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/HttpMethodTransformTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/445

Add http method transform

---

global.json
test/ReverseProxy.Tests/Microsoft.ReverseProxy.Tests.csproj

And remove a pipelines test dependency that was there as a workaround.

Update to the 5.0.0 RTM SDK

---

src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/SessionAffinityConstants.cs
src/ReverseProxy/Middleware/AffinitizeRequestMiddleware.cs
src/ReverseProxy/Middleware/AffinitizedDestinationLookupMiddleware.cs
src/ReverseProxy/Service/Management/ProxyConfigManager.cs
src/ReverseProxy/Service/Proxy/ILoadBalancer.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientContext.cs
src/ReverseProxy/Service/Proxy/LoadBalancer.cs
src/ReverseProxy/Service/RuntimeModel/ClusterConfig.cs
src/ReverseProxy/Service/RuntimeModel/ClusterHealthCheckOptions.cs
src/ReverseProxy/Service/RuntimeModel/ClusterLoadBalancingOptions.cs
src/ReverseProxy/Service/RuntimeModel/ClusterProxyHttpClientOptions.cs
src/ReverseProxy/Service/RuntimeModel/ClusterSessionAffinityOptions.cs
src/ReverseProxy/Service/SessionAffinity/BaseSessionAffinityProvider.cs
src/ReverseProxy/Service/SessionAffinity/CookieSessionAffinityProvider.cs
src/ReverseProxy/Service/SessionAffinity/CustomHeaderSessionAffinityProvider.cs
src/ReverseProxy/Service/SessionAffinity/IAffinityFailurePolicy.cs
src/ReverseProxy/Service/SessionAffinity/ISessionAffinityProvider.cs
src/ReverseProxy/Service/SessionAffinity/RedistributeAffinityFailurePolicy.cs
src/ReverseProxy/Service/SessionAffinity/Return503ErrorAffinityFailurePolicy.cs
src/ReverseProxy/Utilities/TaskUtilities.cs
test/ReverseProxy.Tests/Middleware/AffinityMiddlewareTestBase.cs
test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs
test/ReverseProxy.Tests/Service/Proxy/LoadBalancerTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/ClusterInfoTests.cs
test/ReverseProxy.Tests/Service/SessionAffinity/BaseSesstionAffinityProviderTests.cs
test/ReverseProxy.Tests/Service/SessionAffinity/CookieSessionAffinityProviderTests.cs
test/ReverseProxy.Tests/Service/SessionAffinity/CustomHeaderSessionAffinityProviderTests.cs

- Use a cached Task to represent true and false
- Remove nested classes around session affinity
- Use nameof for SessionAffinityConstants
- Updated calling code and tests
PS: this PR is mostly cosmetic but the nested classes have been bugging me for a long time. There's more but I was looking at the session affinity logic.

Some cleanup

---

src/ReverseProxy/Service/HealthChecks/ActiveHealthCheckMonitor.Log.cs
src/ReverseProxy/Service/HealthChecks/ActiveHealthCheckMonitor.cs

Log status code as integer in order to be consistent with https://github.com/aspnet/Announcements/issues/396

Log HttpStatusCode as int instead of enum

---

test/ReverseProxy.Tests/Service/Management/EntityActionSchedulerTests.cs

This is causing failures on other PRs. Skipping until #508 is addressed.

Skip flaky test

---

src/ReverseProxy/Service/Management/EntityActionScheduler.cs
src/ReverseProxy/Utilities/ITimer.cs
src/ReverseProxy/Utilities/ITimerFactory.cs
src/ReverseProxy/Utilities/TimerFactory.cs
src/ReverseProxy/Utilities/TimerWrapper.cs
test/ReverseProxy.Tests/Service/HealthChecks/ActiveHealthCheckMonitorTests.cs
test/ReverseProxy.Tests/Service/HealthChecks/ReactivationSchedulerTests.cs
test/ReverseProxy.Tests/Service/Management/EntityActionSchedulerTests.cs
test/ReverseProxy.Tests/Utilities/TestTimerFactory.cs

This PR adds `ITimer` abstraction and makes all timer-dependent tests use it to improve their stability and performance.
Fixes #508

ITimer abstracts out a real Timer

---

src/ReverseProxy/Service/Config/ProxyRouteTransformExtensions.cs

Implementing fix discussed in [issue 517](https://github.com/microsoft/reverse-proxy/issues/517). These changes will initialize the ProxyRoute.Transforms property in each of the extension methods if it is null. fixes #517

fix for issue 517, ProxyRouteTransformExtension methods failing when the ProxyRoute.Transforms property is null

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs
test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs

As discussed in issue 458, the HttpClient SendAsync overload changes the response buffering behavior which results in a performance impact. This change performs a downcast check on the httpClient parameter and hard fails if it is of type HttpClient. 
Fixes #458

Performing HttpClient vs HttpMessageInvoker check in HttpProxy

---

src/ReverseProxy/Utilities/ParsedMetadataEntry.cs

Found this little typing error in a utility class, while browsing the repository :)
Cool project!

Throw nameof(cluster) in argument instead of nameof(parser) in ParsedMetaDataEntry

---

test/ReverseProxy.Tests/Service/HealthChecks/TransportFailureRateHealthPolicyTests.cs

We're using invariant culture when parsing the rate limit for health checks, but serializing it with the current culture (`.` vs `,` for floats).
This leads to a spceific test failing on machines with a different culture.

Consistently use InvariantCulture for doubles

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs
test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs

Fixes #467
I'm extending our current WebSockets mitigation to include support for SPDY because that's used by some kubernetes tools.
I also took this chance to reorganize the upgrade logic so it's checked closer to where it's used, and add a little more error handling. That makes it clearer that we only use it to determine the request version.

Handle SPDY upgrades

---

src/ReverseProxy/Service/SessionAffinity/IAffinityFailurePolicy.cs

Allows implementation of custom failure policies, which fixes #595

Change IAffinityFailurePolicy to public

---

src/ReverseProxy.ServiceFabric/Configuration/ServiceFabricServiceCollectionExtensions.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/FabricClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/HealthClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/IFabricClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/PropertyManagementClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/QueryClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/ServiceManagementClientWrapper.cs

Does each one of these wrappers need their own instance of `FabricClient` or is it possible to create only one instance and share it?

Dispose FabricClient

---

test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/DiscovererTests.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/ServiceExtensionLabelsProviderTests.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/CachedServiceFabricCallerTests.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/FabricServiceEndpointSelectorTests.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/527

Remove arrange, act, assert comments from service fabric tests

---

src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ActiveHealthCheckOptions.cs
src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptions.cs
src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/PassiveHealthCheckOptions.cs
src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs
src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/SessionAffinityOptions.cs
src/ReverseProxy/Service/Config/ConfigValidator.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs
src/ReverseProxy/Service/RuntimeModel/ClusterProxyHttpClientOptions.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/531

Make config fields nullable

---

docs/docfx/articles/service-fabric-int.md
src/ReverseProxy.ServiceFabric/Configuration/ServiceFabricServiceCollectionExtensions.cs
src/ReverseProxy.ServiceFabric/ServiceDiscovery/Discoverer.cs
src/ReverseProxy.ServiceFabric/ServiceDiscovery/ServiceExtensionLabelsProvider.cs
src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/CachedServiceFabricCaller.cs
src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/ICachedServiceFabricCaller.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/DiscovererTests.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/ServiceExtensionLabelsProviderTests.cs

Discoverer calls a new `ICachedServiceFabricCaller.CleanUpExpired` method before each discovery cycle to remove expired cached entries. This PR also renames `IServiceFabricCaller` to `ICachedServiceFabricCaller`.

Discoverer cleans up caches by removing expired entries before each iteration

---

src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs

LablesParser doesn't allocate strings while trying to match label keys against known parameter names.
Fixes #586

String allocation-free label key matching in LabelsParser

---

src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/623

Remove default value for DangerousAcceptAnyServerCertificate in ConfigurationConfigProvider

---

src/ReverseProxy.ServiceFabric/FabricWrapper/PropertyManagementClientWrapper.cs
src/ReverseProxy.ServiceFabric/FabricWrapper/QueryClientWrapper.cs
src/ReverseProxy.ServiceFabric/Microsoft.ReverseProxy.ServiceFabric.csproj
src/ReverseProxy/Utilities/Clock.cs

`ValueStopwatch` could replace `Stopwatch` to reduce allocation.
Since `ValueStopwatch` is an internal type in `ReverseProxy` project, I added it to `ReverseProxy.ServiceFabric` as a linked file.

Use ValueStopwatch to reduce allocation

---

contributing.md

Or we could rename the file so it has the same name as it has in ASP.Net Core repository.

Fix the link to the Code of Conduct

---

src/ReverseProxy/Service/Proxy/StreamCopier.cs
test/ReverseProxy.Tests/Service/Proxy/StreamCopyHttpContentTests.cs

Based on findings from https://github.com/microsoft/reverse-proxy/pull/330#issuecomment-758851852
The smaller buffer should bring some perf improvement.

Smaller buffer size for perf.

---

docs/docfx/articles/getting_started.md
docs/docfx/articles/runtimes.md

- We depend on .NET 5, not on previews anymore
- Unify ASP.NET Core vs. .NET references

Docs - unify dependency on .NET 5 references

---

samples/BenchmarkApp/appsettings.json

Results in removing the overhead associated with creating an Activity per request.
Diff should be around 13%.
Note: The HttpClient scenario doesn't suffer from this as it's not calling `Host.CreateDefaultBuilder`, but creating the builder manually.

Disable Hosting.Diagnostics logging

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs

Gives us a bit over 1% RPS
This is the only place where we're using AbsoluteUri, so this change avoids the overhead of computing and storing the string / extra info inside of Uri.

Avoid computing the AbsoluteUri if logging is disabled

---

src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ActivityContextHeaders.cs
src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs
src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs
src/ReverseProxy/Telemetry/ActivityPropagationHandler.cs
test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs
test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs
test/ReverseProxy.Tests/Telemetry/ActivityPropagationHandlerTests.cs

I've added an enum for `ActivityContextHeaders` to support `baggage`, `CorrelationContext` or both.
I also shared the enum between the options model and runtime model which I'm not sure if it's ok. 
Fixes https://github.com/microsoft/reverse-proxy/issues/621

Support baggage header in ActivityPropagationHandler

---

src/ReverseProxy/Service/Proxy/HttpTransformer.cs

The `IEnumerable<string>` for header values returned by the `HttpHeaders` enumerator will always be a `string[]` in Runtime, so we can perform a type check instead of reallocating the array.
https://github.com/dotnet/runtime/blob/65b923ac88979317369a357daca070e5b0164b10/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L345-L346
Saves a `string[]` / every header.

Avoid reallocating the header values array

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs

If `ReasonPhrase` is set, AspNetCore will end up allocating the byte array for it, even if the value is the same as the cached one. This PR avoids setting the field if the value is the default (cached).
https://github.com/dotnet/aspnetcore/blob/e1bda79d87aa712a0b053824b4d31afa2c66cdce/src/Servers/Kestrel/Core/src/Internal/Http/ReasonPhrases.cs#L233
This can be improved in AspNetCore as well.
Saves a `byte[]` and a few `string` allocations / request.

Avoid ReasonPhrase overhead when using default values

---

.gitignore

When running crank benchmarks using a local YARP build, crank will respect the gitignores when uploading the files.
Having this `.pfx` in it means we're not copying the `testCert.pfx` to the perf machines, breaking some runs (https, h2).

Remove *.pfx from gitignore

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs
src/ReverseProxy/Service/Proxy/StreamCopier.cs

Removes some `Task` allocations (3 out of 83 objects or around 4% of allocated bytes).
They are only converted to tasks in `HandleUpgradedResponse`.

Task => ValueTask

---

README.md

Cleaning up some stale comments in the readme about how we report status as Releases rather than on an issue.

Update status reporting in readme

---

src/ReverseProxy/Service/LoadBalancing/ILoadBalancingPolicy.cs
src/ReverseProxy/Service/Proxy/IProxyErrorFeature.cs
src/ReverseProxy/Service/SessionAffinity/IAffinityFailurePolicy.cs
src/ReverseProxy/Service/SessionAffinity/ISessionAffinityProvider.cs

To keep it consistent with the rest of the code base.

Remove access modifier in interfaces

---

eng/Build.props
samples/Directory.Build.props
testassets/Directory.Build.props

Our `/samples` and `/testassets` folders are not built as part of the PR, CI, or command line flow, making them prone to getting out of date and breaking. They only build by default in VS.
When I enabled the build for those folders I got the following error:
```
D:\github\reverse-proxy\.dotnet\sdk\5.0.103\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(194,6): error : This project cannot be packaged because packaging has been disabled. Add <IsPackable>true</IsPackable> to the project file to enable producing a package from this project. [D:\github\reverse-proxy\samples\ReverseProxy.ServiceFabric.Sample\ReverseProxy.ServiceFabric.Sample.csproj]
```
`<WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>` works around this but it's not clear …

Build samples and test assets

---

src/ReverseProxy/Service/Management/ProxyConfigManager.cs

A missing double quotation is breaking the GitHub styling.
Before:
After:

Fix ProxyConfigManager remarks

---

src/ReverseProxy/Service/Config/ConfigValidator.cs
test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs

Removing the hosts name regex validation as the hostname is not coming from user input.
#25

remove hosts regex validator from configvalidator

---

src/ReverseProxy/EventIds.cs
src/ReverseProxy/Middleware/AffinitizedDestinationLookupMiddleware.cs
src/ReverseProxy/Middleware/DestinationInitializerMiddleware.cs
src/ReverseProxy/Middleware/HttpContextFeaturesExtensions.cs
src/ReverseProxy/Middleware/IReverseProxyFeature.cs
src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs
src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs
src/ReverseProxy/Middleware/ReverseProxyFeature.cs
src/ReverseProxy/Service/Management/ProxyConfigManager.cs
src/ReverseProxy/Service/RuntimeModel/RouteConfig.cs
src/ReverseProxy/Service/SessionAffinity/AffinitizeTransform.cs
test/ReverseProxy.Tests/DynamicEndpoint/ReverseProxyConventionBuilderTests.cs
test/ReverseProxy.Tests/Middleware/AffinityMiddlewareTestBase.cs
test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/PassiveHealthCheckMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactoryTests.cs
test/ReverseProxy.Tests/Service/Proxy/LoadBalancingPoliciesTests.cs
test/ReverseProxy.Tests/Service/SessionAffinity/AffinitizeTransformTests.cs

This addresses design feedback from a review session we did this week. The focus was on middleware extensibility scenarios and ensuring a good public API surface. Some highlights:
- We've removed some of the short circuits that would happen when entering the proxy pipeline, such as if there were no healthy destinations. The pipeline now executes so you can customize what happens.
- We also removed short circuits from load balancing. Error responses are now primarily returned from the end of the pipeline.
- Naming of properties on IReverseProxyFeature.
- Route data is now included on IReverseProxyFeature. Fixes https://github.com/microsoft/reverse-proxy/issues/587

Design review feedback

---

src/ReverseProxy/Utilities/TlsFrameHelper.cs
testassets/ReverseProxy.Direct/Program.cs
testassets/ReverseProxy.Direct/TlsFilter.cs
testassets/ReverseProxy.Direct/appsettings.json

Fixes #813 Partners are going to need this feature soon. I'm making the current types public and adding an example to consume them as a kestrel connection middleware.

Make TlsFrameHelper public 

---

NuGet.config
docs/docfx/articles/getting_started.md
docs/docfx/articles/service-fabric-int.md
docs/docfx/articles/session-affinity.md
samples/BasicYarpSample/BasicYarpSample.csproj
samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj
samples/ReverseProxy.Code.Sample/InMemoryConfigProvider.cs
samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj
samples/ReverseProxy.Code.Sample/Startup.cs
samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs
samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj
samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj
samples/ReverseProxy.Direct.Sample/Startup.cs
samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj
samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj
samples/ReverseProxy.Transforms.Sample/MyTransformFactory.cs
samples/ReverseProxy.Transforms.Sample/MyTransformProvider.cs
samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj
samples/ReverseProxy.Transforms.Sample/Startup.cs
src/ReverseProxy/Service/SessionAffinity/CustomHeaderSessionAffinityProvider.cs

Contributes to #811
I've updates these samples temporarily using packages from our daily builds on the dotnet5 feed. Normally we'd wait for a nuget.org release, but there are more changes here than usual that I wanted done in time for the release. We should plan to push the newly branded packages to nuget next week.

Update package dependent samples 

---

src/ReverseProxy/Utilities/IsExternalInit.cs

C# 9 features like init only properties weren't officially supported on .NET Core 3.1, though it can be used with the 5.0 SDK and a copy of the IsExternalInit class (which we were told by Jared to make public). 
cc: @davidni we'll see if this being public means that you don't have to add your own copy.

Make IsExternalInit public

---

docs/docfx/articles/configproviders.md
docs/docfx/index.md

#844
These 2 docs commits were only made into release/docs and the auto-merge failed because of Microsoft => Yarp xref changes.

Release10 merge docs release

---

src/ReverseProxy/Service/Proxy/HttpTransformer.cs
src/ReverseProxy/Utilities/RequestUtilities.cs

Addresses design feedback.
HttpTransformer.TransformRequestAsync has all request fields populated before it's called except headers and the RequestUri as those are the most commonly transformed. There are some tricks to creating the request uri correctly and efficiently, so we're making this API public to help people get it right.

Make MakeDestinationAddress public

---

src/ReverseProxy/Service/Proxy/HttpProxy.cs
testassets/TestClient/Program.cs
testassets/TestClient/Scenarios/Http2PostExpectContinueScenario.cs
testassets/TestServer/Controllers/HttpController.cs

Handle `Expect:100-continue` when destination chooses not to accept request body

---

src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
src/ReverseProxy/Service/Config/ConfigValidator.cs
test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs

HostMatcherPolicy will accept host names in punycode, but AspNetCore always tries to match against the unicode form of the request host.
This change gives Yarp users a warning in this case, where the entry would effectively get ignored.
I tested that Yarp works with `ünicode`, but not `xn--nicode-2ya` as the host.
Fixes #25

Disallow punycode host names in config

---

src/ReverseProxy/Service/RuntimeModel/DestinationInfo.cs
test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
test/ReverseProxy.Tests/Service/Proxy/LoadBalancingPoliciesTests.cs

Addresses design review feedback. Someone writing an ILoadBalancingPolicy that depends on the ConcurrentRequestCount for destinations wouldn't be able to test it since that property can only be modified internally.

Make DestinationInfo.ConcurrentRequestCount settable

---

docs/docfx/articles/direct-proxying.md
docs/docfx/articles/middleware.md
docs/docfx/articles/toc.yml
src/ReverseProxy/Middleware/DestinationInitializerMiddleware.cs
src/ReverseProxy/Middleware/HttpContextFeaturesExtensions.cs
src/ReverseProxy/Middleware/IReverseProxyFeature.cs
src/ReverseProxy/Service/SessionAffinity/AffinitizeTransform.cs
test/ReverseProxy.Tests/Middleware/PassiveHealthCheckMiddlewareTests.cs
test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
test/ReverseProxy.Tests/Service/Proxy/LoadBalancingPoliciesTests.cs
testassets/ReverseProxy.Direct/Startup.cs

Fixes #114 - Docs for customizing functionality through ASP.NET middleware.
Fixes #878 - Testing middleware: Re-implements middleware helpers like GetRequiredCluster to fetch their information from the IReverseProxy feature rather than the endpoint, only DestinationInitializerMiddleware accesses the endpoint directly to create the feature. I've also moved these extensions to the same namespace as HttpContext.
cc: @jmezach

Middleware docs and helper API cleanup

---

docs/docfx/articles/proxyhttpclientconfig.md
src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
src/ReverseProxy/Service/Proxy/Infrastructure/CallbackProxyHttpClientFactory.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs
testassets/ReverseProxy.Code/Startup.cs

Fixes #805 Make ProxyHttpClientFactory public and extensible
Fixes #843 (@berhir) Enable adding HttpMessageHandler middleware (e.g. DelegatingHandler)
Contributes to #801 Allow using ProxyHttpClientFactory for direct IHttpProxy scenarios
ProxyHttpClientFactory is now public so people can: 
A) Create it directly when using IHttpProxy
B) Derive from it to customize the SocketHttpHandler settings without completely re-implementing IProxyHttpClientFactory
C) Derive from it to enable wrapping SocketHttpHandler with DelegatingHandler middleware.
There's also a new extension for simple scenarios:
```C#
services.AddReverseProxy()
.ConfigureClient((context, handler) =>
{
handler.Expect100ContinueTimeout = TimeSpan.FromMilliseconds(300);
})
```

Make ProxyHttpClientFactory public and extensible 

---

src/ReverseProxy/Abstractions/Config/ITransformBuilder.cs
src/ReverseProxy/Service/Config/TransformBuilder.cs
testassets/ReverseProxy.Direct/Startup.cs

- Is it ok that `Cluster` and `ProxyRoute` is null in context? or should there be another type and change all extensions method?
- Should there be any default transform in `Create` (e.g. X-Forwarded) ? 
Fixes https://github.com/microsoft/reverse-proxy/issues/801

Add ITransformBuilder.Create method

---

samples/ReverseProxy.Code.Sample/Startup.cs

This sample uses a wildcard package dependency and couldn't be updated until there was a build available.

React to API breaks in samples

---

samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusServiceExtensions.cs
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/Startup.cs
src/ReverseProxy.TelemetryConsumption/EventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Http/HttpEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Http/IHttpTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/Kestrel/IKestrelTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/Kestrel/KestrelEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/NameResolution/INameResolutionTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/NameResolution/NameResolutionEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/NetSecurity/INetSecurityTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/NetSecurity/NetSecurityEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Proxy/IProxyTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/Proxy/ProxyEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Sockets/ISocketsTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/Sockets/SocketsEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/TelemetryConsumptionExtensions.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs
testassets/ReverseProxy.Code/Startup.cs

Replacement for #915, description is NOT the same
Removed the `AddProxyTelemetryListener`, `AddHttpTelemetryListener`, ... extension methods as they don't provide any benefit over just `AddTelemetryListeners` after this change.
The listeners no longer fetch consumers per request (`GetServices`) - instead they get the consumers injected in the constructor. This means the core listeners only respect singleton consumers.
If needed, we can expose wrappers/helpers that add scoped consumer lifetimes.
Added an abstract `EventListenerService` class as a base of all listeners.
It abstracts away the synchronization around enabling the EventSource based on parameters from the constructor.
The listener implementations now only enable the necessary `EventSource`s with the needed parameters. We will …

Only enable events/counters if there are listeners available

---

samples/ReverseProxy.Metrics.Sample/Startup.cs
src/ReverseProxy.TelemetryConsumption/TelemetryConsumptionExtensions.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs

Now that the build of #931 produced updated packages, react to the removal of `Add*TelemetryListener`.
Also adding tests for the helper APIs added in #928.

React to Telemetry Consumption API change and add tests

---

.github/workflows/docfx_build.yml
docs/docfx/articles/direct-proxying.md
docs/docfx/articles/getting_started.md
docs/docfx/readme.md
docs/operations/Release.md
samples/BasicYarpSample/BasicYarpSample.csproj
samples/BasicYarpSample/appsettings.json
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/ReverseProxy.Metrics.Promethius.Sample.csproj
samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj
samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj
samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj
samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj
samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj
samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj
samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj
samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj

#940
Brings over the rename from `release/docs` to `release/latest`.
Added `LangVersion` to samples to allow building them standalone (without our `Directory.Build.props` definitions).
Fixed a config issue for `BasicYarpSample` that would cause it to crash at startup.
Updated Samples' nuget package versions to the actual publicly released version.

Merge preview11 changes into main

---

src/ReverseProxy/Configuration/DependencyInjection/BuilderExtensions/IReverseProxyBuilderExtensions.cs
src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs

Fixes #949 
ITransformBuilder recently added the Create API for use with IHttpProxy, but ITransformBuilder isn't actually registered in DI by AddHttpProxy. This moves the registration down a layer.
cc: @leastprivilege

Make ITransformBuilder available for IHttpProxy 

---

.config/CredScanSuppressions.json
eng/PoliCheckExclusions.xml

We don't have a `PoliCheckExclusions` file in this repo. Fixing that config uncovers the issue that the benchmark app key has moved since we added the CredScan suppression for it.

Fix SDL config and update CredScan suppression

---

samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusDnsMetrics.cs
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusKestrelMetrics.cs
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusOutboundHttpMetrics.cs
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusServiceExtensions.cs
samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/PrometheusSocketMetrics.cs
src/ReverseProxy.Kubernetes.Protocol/Receiver.cs
src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
src/ReverseProxy.TelemetryConsumption/Kestrel/IKestrelTelemetryConsumer.cs
src/ReverseProxy.TelemetryConsumption/Kestrel/KestrelEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/TelemetryConsumptionExtensions.cs
src/ReverseProxy/Configuration/CertificateConfigLoader.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/QueryTransformContext.cs
src/ReverseProxy/Utilities/ProtocolHelper.cs
src/ReverseProxy/Utilities/TlsFrameHelper.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs
test/ReverseProxy.Tests/Configuration/CertificateConfigLoaderTests.cs

Consistently use #if NET

---

azure-pipelines.yml
eng/Publishing.props

Based on https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3
[This change on an internal test branch](https://dev.azure.com/dnceng/internal/_build/results?buildId=1121034&view=results)
Fixes #968

Move to v3 publishing

---

docs/docfx/articles/transforms.md
src/ReverseProxy/Abstractions/Config/RequestHeadersTransformExtensions.cs
src/ReverseProxy/Abstractions/Config/ResponseTransformExtensions.cs
src/ReverseProxy/Service/Config/RequestHeadersTransformFactory.cs
src/ReverseProxy/Service/Config/ResponseTransformFactory.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/QueryParameterFromStaticTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/QueryParameterTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/QueryTransformContext.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderRemoveTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderValueTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseHeaderRemoveTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTrailerRemoveTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTrailersTransform.cs
src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTransform.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/QueryParameterFromStaticTransformTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/RequestHeaderRemoveTransformTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/ResponseHeaderRemoveTransformTests.cs
test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/ResponseTrailerRemoveTransformTests.cs
test/ReverseProxy.Tests/Utilities/TestResources.cs

Adds support for empty string value in QueryParameterTransform. It changes the way the empty string "" value is handled, now it doesn't remove the given query parameter or header anymore, instead the "" is treated as a normal string value. To remove a query parameter the existing QueryParameterRemoveTransform can be used. To remove headers, the new transforms RequestHeaderRemoveTransform, ResponseHeaderRemoveTransform, and ResponseTrailerRemoveTransforms are added by this PR.
Note, setting "" as a header value is not recommended and can cause an undefined behavior.
Fixes #619

Empty values in QueryParameterTransform and headers *Remove transforms

---

src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
src/ReverseProxy/Abstractions/HttpClientConfig.cs
src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
src/ReverseProxy/Service/Config/ConfigValidator.cs
src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs
test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs
test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptionsTests.cs
test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs

Contributes to #352
We have multiple providers that use System.Text.Json to serialize the config model across processes. The Encoding type doesn't serialize, so I've changed the config model to flow the encoding by name and resolve it to an instance later.

Flow RequestHeaderEncoding as a string

---

docs/operations/Release.md

Fixes #935
[New checklist](https://github.com/microsoft/reverse-proxy/issues/new?title=Preview%20X%20release%20checklist&body=See%20%5BRelease.md%5D%28https%3A%2F%2Fgithub.com%2Fmicrosoft%2Freverse-proxy%2Fblob%2Fmain%2Fdocs%2Foperations%2FRelease.md%29%20for%20detailed%20instructions.%0A%0A-%20%5B%20%5D%20Ensure%20there%27s%20a%20release%20branch%20created%20%28see%20%5BBranching%5D%28https%3A%2F%2Fgithub.com%2Fmicrosoft%2Freverse-proxy%2Fblob%2Fmain%2Fdocs%2Foperations%2FBranching.md%29%29%0A-%20%5B%20%5D%20Ensure%20the%20%60Version.props%60%20has%20the%20%60PreReleaseVersionLabel%60%20updated%20to%20the%20next%20preview%0A-%20%5B%20%5D%20Identify%20and%20validate%20the%20build%20on%20the%20%60microsoft-reverse-proxy-official%60%20pipeline%0A-%20%5B%20%5D%20Release%20the%20build%0A-%20%5 …

Include updating sample package references in release checklist

---

test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs
test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs

Fixes #352 By adding regression tests.
After #995 (Encoding) and #994 (X509Certificate) were resolved the only types left in the config model that can't be deserialized by default are TimeSpan and Version. These are both being fixed in .NET 6 and have easy workarounds so I'm content to leave them.
~~Marking as draft until I can include the new entries from #997 (Session Affinity cookies).~~

Add json serialization tests

---

src/ReverseProxy.TelemetryConsumption/EventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Http/HttpEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Kestrel/KestrelEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/NameResolution/NameResolutionEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/NetSecurity/NetSecurityEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Proxy/ProxyEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Sockets/SocketsEventListenerService.cs
src/ReverseProxy.TelemetryConsumption/Yarp.ReverseProxy.Telemetry.Consumption.csproj

Public API stays the same (all non-null)
Contributes to #654

Enable nullable on TelemetryConsumption

---

src/ReverseProxy/Service/Proxy/EmptyHttpContent.cs
src/ReverseProxy/Utilities/RequestUtilities.cs
test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs

Fixes #618
Headers defined as `HttpHeaderType.Content` in [KnownHeaders.cs](https://github.com/dotnet/runtime/blob/c90debb5dc8ee85840bbef1a44b8502ab169f47b/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L28-L61) may only be present in the `HttpContentHeaders` collection.
To avoid dropping such headers when there is no request body (e.g. `Content-Length` is 0), we inject a dummy 0-length content object to hold the headers.

Don't drop content-specific headers on requests without a body

---

docs/docfx/articles/proxyhttpclientconfig.md

This mitigates the lack of client certificate support in the config (https://github.com/microsoft/reverse-proxy/issues/999) by showing how to configure it programmatically.

Show sample of a client certificate

---

src/ReverseProxy/Service/HealthChecks/ActiveHealthCheckMonitor.cs
src/ReverseProxy/Service/HealthChecks/DefaultProbingRequestFactory.cs
test/ReverseProxy.Tests/Service/HealthChecks/ActiveHealthCheckMonitorTests.cs

Fixes #991
Since the user can specify a custom `IProbingRequestFactory`, they can already set a custom `User-Agent` for active health check requests.
Added a test to ensure we don't break that scenario - we only add the default value if one is not already provided.
Currently: `YARP Active Health Check Monitor`

Set default User-Agent for active health check requests

---

src/ReverseProxy/Utilities/TlsFrameHelper.cs
test/ReverseProxy.Tests/Utilities/TlsFrameHelperTests.cs

this is basic implementation to cover  #1023.
Adding support for server e.g. negotiated cipher should not be difficult but I was not sure if it is needed. 
We would probably add ushort/TlsCipherSuite instead of exposing it as array of size 1.
I did chat with @davidfowl about array pools but I'm not sure if that is really needed. I decided to expose the set as Memory so one can play with that later if needed. 
Note that this PR exposes the raw set e.g. can have values outside of TlsCipherSuite enum. 
That is for example 65413 in the test e.g. GOST or 255 e.g. pseudo renegotiation cipher from rfc5746
cc; @Tratcher @davidfowl 
fixes  #1023

add cipher info to tls parser

---

src/ReverseProxy/Utilities/TlsFrameHelper.cs

as mentioned in https://github.com/microsoft/reverse-proxy/pull/1026#discussion_r640079973 used options.HasFlag.
also corrected `ProcessingOptions.All` to `0x7FFFFFFF`
fixes https://github.com/microsoft/reverse-proxy/pull/1026

Using options.HasFlag

---

docs/docfx/articles/grpc.md
docs/docfx/articles/toc.yml

Fixes #952
Contributes to #118
There's a lot of interest in YARP for proxying gRPC so we want an explicit doc calling it out. It doesn't require much special handling unless you want to do it without TLS.

Doc gRPC scenarios 

---

src/ReverseProxy/Proxy/RequestUtilities.cs
test/ReverseProxy.Tests/Proxy/HttpProxyTests.cs

TE header only applies to the immediate connection, so it should be removed from proxied requests.
Fixes #969

Remove TE header from proxied requests

---

docs/docfx/articles/configfiles.md

The comment:
> // Lower numbers have higher precidence
Should read:
> // Lower numbers have higher **precedence**

Fix small typo in configfiles.md

---

src/ReverseProxy/Forwarder/ForwarderTelemetry.cs

There is a very subtle difference between the two:
- The current version (passing the name in ctor) uses the public `EventSource` constructor, which sets the `EtwSelfDescribingEventFormat` option.
- The new version (attribute) uses the empty ctor, which is a protected one that sets `EtwManifestEventFormat` instead.
There are some subtle differences (for example bools are encoded with 1 vs 4 bytes).
This PR makes us consistent with what all other `EventSource`s do.
`dotnet trace` appears to have problems working with `EtwSelfDescribingEventFormat`, which can be observed as garbage data for events that include a bool.
cc: @alnikola this is what you have been seeing in the past
Related to #1079
Opened an issue in diagnostics regarding `dotnet trace`: dotnet/diagnostics#2367

Pass EventSource name via attribute

---

docs/docfx/articles/transforms.md

In previous versions it was the explicit `""`string, by now it is `"Off"` as referenced multiple times above and below.

Fix off setting description in do X-Forwarded doc

---

docs/docfx/articles/config-providers.md

I copy and pasted the same code into the test project and found the two using statements are no longer needed and/or valid.

Removed invalid/unneeded using statements

---

docs/docfx/articles/transforms.md
src/ReverseProxy/Transforms/RequestHeadersAllowedTransform.cs
src/ReverseProxy/Transforms/RequestHeadersTransformExtensions.cs
src/ReverseProxy/Transforms/RequestHeadersTransformFactory.cs
src/ReverseProxy/Transforms/ResponseHeadersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseTrailersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseTransformExtensions.cs
src/ReverseProxy/Transforms/ResponseTransformFactory.cs
test/ReverseProxy.Tests/Transforms/RequestHeadersAllowedTransformTests.cs
test/ReverseProxy.Tests/Transforms/RequestHeadersTransformExtensionsTests.cs
test/ReverseProxy.Tests/Transforms/ResponseHeadersAllowedTransformTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTrailersAllowedTransformTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTransformExtensionsTests.cs

Fixes #1114. YARP copies request and response headers by default. A security conscious admin may want to only allow specific headers in or out. This PR implements allow lists for request headers, response headers and response trailers as per route transforms.
I also backfilled some tests for the Request/Response/Trailers Remove transforms and fixed a bug with ResponseHeaderRemove using the wrong key. (Fixes #1141)

Implement header allow lists

---

test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs
test/ReverseProxy.FunctionalTests/HeaderEncodingTests.cs

It adds functional tests for the scenarios listed below.
The first scenario set is based on [this list](https://github.com/microsoft/reverse-proxy/issues/617#issuecomment-852243785), but modified to be compatible with the actual HttpClient behavior.
- A. HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
- B. HTTP/1.1 POST with a Transfer-Encoding is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
- C. A & B proxied over HTTP/2
- D. HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 4xx, the data is not uploaded. …

Expect: 100-continue functional tests w/ and w/o response body

---

src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs

Contributes to #708
This matches the default used by runtime
https://github.com/dotnet/runtime/blob/c83b6edc1c1f500565bc5d53cfd726463ce2f56b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DistributedContextPropagator.cs#L123
and will make the change smaller if/when we remove the `ActivityPropagationHandler` from YARP.

Set ActivityContextHeaders default to CorrelationContext only

---

src/ReverseProxy/Health/TransportFailureRateHealthPolicy.cs
test/ReverseProxy.Tests/Health/TransportFailureRateHealthPolicyTests.cs

When `TransportFailureRatePolicy` is configured with ReactivationPeriod < DetectionWindowSize, an unhealthy destination sent for cool down and then reactivated can be marked as unhealthy on the first request right after reactivation even if such a request completed successfully.
To avoid that issue, we will use the max of reactivation and detection periods for the reactivation delay.
Fixes #1082

Use the max of reactivation and detection periods for reactivation delay

---

src/ReverseProxy/Forwarder/HttpTransformer.cs
test/ReverseProxy.FunctionalTests/HeaderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.3
```
If a message is received with both a Transfer-Encoding and a
Content-Length header field, the Transfer-Encoding overrides the
Content-Length.  Such a message might indicate an attempt to
perform request smuggling (Section 9.5) or response splitting
(Section 9.4) and ought to be handled as an error.  A sender MUST
remove the received Content-Length field prior to forwarding such
a message downstream.
```
We've decided to remove the Content-Length header in this scenario as a precaution.

Remove the Content-Length header

---

src/ReverseProxy/Forwarder/HttpTransformer.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

Fixes #1191 TE is normally a hop-by-hop header, but the `trailers` value is special and should be preserved. Some gRPC servers require this.

Preserve the TE: trailers header 

---

docs/operations/BackportingToPreview.md

Clarifying some points in the patching instructions:
- A patch is a new release. Do not edit prior releases or delete prior tags.
- Use the full build number to identify patch releases.
E.g. Preview 12 was tagged as v1.0.0-preview12. The patch for preview12 was tagged as v1.0.0-preview12.21451.3.

Update the patching instructions

---

.editorconfig
samples/ReverseProxy.ConfigFilter.Sample/CustomConfigFilter.cs
src/ReverseProxy/Configuration/IProxyConfigFilter.cs
src/ReverseProxy/Management/ProxyConfigManager.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs
testassets/ReverseProxy.Config/CustomConfigFilter.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/1229

Add cluster to ConfigureRouteAsync

---

src/ReverseProxy/Transforms/Builder/TransformHelpers.cs
src/ReverseProxy/Transforms/ForwardedTransformExtensions.cs
src/ReverseProxy/Transforms/ForwardedTransformFactory.cs
src/ReverseProxy/Transforms/RequestHeaderForwardedTransform.cs
src/ReverseProxy/Utilities/NullRandomFactory.cs
test/ReverseProxy.Tests/Transforms/Builder/TransformBuilderTests.cs
test/ReverseProxy.Tests/Transforms/ForwardedTransformExtensionsTests.cs

If X-Forwarded-* transforms are enabled by any way (default or manually), a transform removing Forwarded header is added automatically. On the opposite, if Forwarded transform is added, the transforms removing all X-Forwarded-* headers are added automatically.
Fixes #1070

Remove Forwarded header when X-Forwarded transforms added and vice versa

---

src/ReverseProxy.Kubernetes.Controller/Caching/ICache.cs
src/ReverseProxy.Kubernetes.Controller/Caching/IngressCache.cs
src/ReverseProxy.Kubernetes.Controller/Caching/NamespaceCache.cs
src/ReverseProxy.Kubernetes.Controller/Caching/ServiceData.cs
src/ReverseProxy.Kubernetes.Controller/Converters/YarpIngressContext.cs
src/ReverseProxy.Kubernetes.Controller/Converters/YarpParser.cs
src/ReverseProxy.Kubernetes.Controller/Services/IngressController.cs
src/ReverseProxy.Kubernetes.Controller/Services/ReconcileData.cs
src/ReverseProxy.Kubernetes.Controller/Services/Reconciler.cs
src/ReverseProxy.Kubernetes.Controller/Startup.cs
test/ReverseProxy.Kubernetes.Tests/IngressConversionTests.cs
test/ReverseProxy.Kubernetes.Tests/testassets/basic-ingress/ingress.yaml
test/ReverseProxy.Kubernetes.Tests/testassets/exact-match/ingress.yaml
test/ReverseProxy.Kubernetes.Tests/testassets/mapped-port/clusters.json
test/ReverseProxy.Kubernetes.Tests/testassets/mapped-port/ingress.yaml
test/ReverseProxy.Kubernetes.Tests/testassets/mapped-port/routes.json
test/ReverseProxy.Kubernetes.Tests/testassets/multiple-endpoints-ports/ingress.yaml

- Added watching and caching of Kubernetes Service resources
- Skip reconciliation until Service and Ingress resources are both retrieved
- Changed cluster_id to use Service name and port name/number
For the tests:
- Added Services to Kubernetes unit tests (ingress.yaml files)
- Added test for different port/targetPort configured in Service (as per #1162)

Add support for Kubernetes Services (#1162)

---

samples/ReverseProxy.Direct.Sample/README.md
src/ReverseProxy/Forwarder/HttpTransformer.cs
src/ReverseProxy/Transforms/Builder/TransformBuilder.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

Use the same default transformer for HttpForwarder and the whole YARP

---

samples/ReverseProxy.Metrics.Sample/Startup.cs
samples/ReverseProxy.Metrics.Sample/WebSocketsTelemetryConsumer.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Utilities/DelegatingStream.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketCloseReason.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsParser.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetry.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryExtensions.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryMiddleware.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs
src/TelemetryConsumption/TelemetryConsumptionExtensions.cs
src/TelemetryConsumption/WebSockets/IWebSocketsTelemetryConsumer.cs
src/TelemetryConsumption/WebSockets/WebSocketCloseReason.cs
src/TelemetryConsumption/WebSockets/WebSocketsEventListenerService.cs
test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
test/ReverseProxy.FunctionalTests/HeaderTests.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs
test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/WebSocketsTelemetry/WebSocketsParserTests.cs
test/Tests.Common/ManualClock.cs

Fixes #1209
I followed the approach outlined in #1209 of wrapping the upgrade feature and MITM the upgrade transport stream.
Public API is just the `UseWebSocketsTelemetry` extension method.
I fed the data to an `EventSource` event, but it could also alternatively be something like `IWebSocketsTelemetryFeature`.
I didn't know where to put the code so I made a `WebSocketsTelemetry` folder in the main project (all types are internal though).
ToDo: I will add tests when we're happy with the overall approach

Add WebSockets telemetry

---

azure-pipelines.yml

We're required to move all servicing branches to the new 1ES servicing pools by September 30. This accomplishes that for release/latest.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276

Move to 1ES servicing pools in release/latest

---

docs/operations/Branching.md

Until servicing pools are used for all branches, we will have to update the pool configuration when creating new release branches.
See #1265

Update branching docs to include changing build pools

---

src/ReverseProxy/Forwarder/RequestUtilities.cs
test/ReverseProxy.Tests/Forwarder/RequestUtilitiesTests.cs

Fixes #1219
The default PathString.ToUriComponent() doesn't round trip all the encoded values we want so we now encode it ourselves.

Clean up proxy url generation 

---

src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj
src/Kubernetes.Protocol/Yarp.Kubernetes.Protocol.csproj
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/ProtocolHelper.cs
src/ReverseProxy/Transforms/ResponseTrailerRemoveTransform.cs
src/ReverseProxy/Transforms/ResponseTrailersTransform.cs
src/ReverseProxy/Yarp.ReverseProxy.csproj
src/ServiceFabric/Yarp.ReverseProxy.ServiceFabric.csproj
src/TelemetryConsumption/Yarp.Telemetry.Consumption.csproj
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Contributes to #1055
Since .NET 6.0 is nearly released we're adding the TFM to our packages to indicate that it's supported. We were already running tests for this TFM.
Targeting 6.0 added a few new nullability warnings that I've addressed here. One is an interesting corner case where the destination could return a 101 response even if the request did not support upgrades.

Add the net6.0 TFM

---

src/ServiceFabric/Yarp.ReverseProxy.ServiceFabric.csproj

The SF work is continuing out of band and will not ship as part of YARP 1.0.

Disable packing/shipping the ServiceFabric package

---

docs/docfx/README.md
docs/docfx/articles/header-guidelines.md
docs/docfx/articles/toc.yml

Document header concerns 

---

docs/docfx/articles/https-tls.md
docs/docfx/articles/toc.yml

Contributes to #305. We may want to add some more kestrel specific examples, but this seamed like a good starting point.

HTTPS & TLS docs 

---

src/OperatorFramework/test/UnitTests/Controller/Queues/DelayingQueueTests.cs
src/OperatorFramework/test/UnitTests/Controller/Rate/LimiterTests.cs

Another flaky test from `Microsoft.Kubernetes.UnitTests` (#1333).
Failed on main for #1341
Cleaning up CI for #1353

Skip LimiterTests.ManyWaitsStackUp

---

eng/Versions.props

Fixes #1317
Contributes to #1353
Should we be switching `main` to `1.1.0.preview.1` or drop the preview altogether `1.1.0`?

Remove PreReleaseVersionLabel

---

azure-pipelines.yml

Resolves CI build warning:
```
##[warning]The macOS-10.14 environment is deprecated and will be removed on December 10, 2021. For more details see https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
```

Update CI to macos-latest

---

samples/Directory.Build.props
samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj

Fixes #1363
The symbols build error was caused by our samples defaulting to IsShipping and doing more verification than needed.

Enable net6.0 in auth sample 

---

src/ReverseProxy/Forwarder/StreamCopier.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopierTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopyHttpContentTests.cs

Fixes #1325
I moved all the telemetry-related logic into a separate `StreamCopierTelemetry` class to both simplify the code and reduce the size of the `CopyAsync` state machine. Also removed the try-finally blocks to minimize the overhead.
This change amounts to a 5.6% RPS improvement in our base (http-http 100-byte) benchmark.
About 4.6% of which comes the fact we are no longer clearing the entire rented ArrayPool buffer on both sides.
The extra 1% comes from the simplified `CopyAsync` implementation, even after you account for the extra work we are doing to issue the zero-byte read.
Memory-wise, for a persistent idle connection (e.g. WebSockets), we avoid holding onto the 64k buffer on the request content side. With support from runtime, we also avoid holding the 64k buffer on the …

Use zero-byte reads in StreamCopier

---

test/ReverseProxy.Tests/Utilities/TlsFrameHelperTests.cs

Fixes #473 
Moving 3980 generated cases into one test to not break XUnit limits and get valid results.

Put generated `InvalidClientHelloDataTruncatedBytes` data into one test

---

src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs

Followup to #1415
A `Consume` of zero bytes is a no-op on the parser, so we can just return the original read task to the caller.
Since we are always doing zero-byte reads, this effectively means that if the underlying stream supports it, `WebSocketsTelemetryStream`'s `ReadAsync` will never allocate.

Fast-path zero-byte reads in WebSocketsTelemetryStream ReadAsync

---

src/ReverseProxy/Forwarder/HttpTransformer.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/1409

Add Empty HttpTransformer

---

samples/KuberenetesIngress.Sample/Ingress/Dockerfile
src/Kubernetes.Controller/Dockerfile

Fixes the following docker image build error:
When using COPY with more than one source file, the destination must be
a directory and end with a /

Fixes build of docker image

---

samples/ReverseProxy.Metrics.Sample/README.md

Previously the heading wasn't rendered correctly as there was no space after the #. Just added the #

Fixed invalid heading markdown for Metrics.Sample Readme

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/StreamCopier.cs
src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopierTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopyHttpContentTests.cs

Fixes #1412 
Throwing an exception when `Content-Length` is set but doesn't match with actual length in request. This allows to avoid unclear hangings as described in the issue above.

Throw on wrong Content-Length

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/HttpTransformer.cs
src/ReverseProxy/Forwarder/RequestUtilities.cs
src/ReverseProxy/Transforms/QueryParameterRemoveTransform.cs
src/ReverseProxy/Transforms/RequestHeaderOriginalHostTransform.cs
src/ReverseProxy/Transforms/RequestHeaderValueTransform.cs
src/ReverseProxy/Transforms/RequestTransform.cs
src/ReverseProxy/Transforms/ResponseHeaderValueTransform.cs
src/ReverseProxy/Transforms/ResponseHeadersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseTrailerValueTransform.cs
src/ReverseProxy/Transforms/ResponseTrailersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseTrailersTransform.cs
src/ReverseProxy/Transforms/ResponseTransform.cs
test/ReverseProxy.Tests/Forwarder/RequestUtilitiesTests.cs

Closes #1347
Memory-wise, we go from 64 objects to 38 (-41%), or 4366 B to 3180 (-27%) per request.
RPS-wise, this change is a win of ~5-6% on citrine and ~7% on perf machines. Closes #1083
Before:
After:
We save 26 objects:
- 8x `string`
- 5x `string[]`
- 4x `HeaderStoreItemInfo`
- 4x (`MediaType`/`NameValue`/`Product`/`ProductInfo`)`HeaderValue`
- 2x `HttpHeadersEnumerator`
- 1x `ObjectCollection`
- 1x `Uri`
- 1x `DateTimeOffset` (box)

Make use of NonValidated headers

---

src/ReverseProxy/Transforms/Builder/StructuredTransformer.cs
test/ReverseProxy.Tests/Transforms/Builder/TransformBuilderTests.cs

We're storing the transforms as `IList`s, which means every `foreach` over them allocates (enumerator gets boxed).
These are internal, so we can just avoid the overhead by storing an array instead.

Avoid boxing ILIst enumerators per request

---

docs/docfx/articles/direct-forwarding.md
docs/docfx/articles/header-guidelines.md
samples/ReverseProxy.Direct.Sample/Startup.cs
src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs
src/ReverseProxy/Forwarder/RequestUtilities.cs
src/ReverseProxy/Forwarder/ReverseProxyPropagator.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

Resolves #1497 
Added `ReverseProxyPropagator` that handles headers removal. Default inner implementation removes distributed context headers. It can be changed by overriding `Propagator` property in `ForwarderHttpClientFactory` which is used to set up `handler.ActivityHeadersPropagator`.

Handle distributed context headers in custom propagator

---

docs/docfx/articles/authn-authz.md
docs/docfx/articles/config-files.md
docs/docfx/articles/config-providers.md
docs/docfx/articles/cors.md
docs/docfx/articles/direct-forwarding.md
docs/docfx/articles/http-client-config.md
docs/docfx/articles/kubernetes-ingress.md
docs/docfx/articles/load-balancing.md
docs/docfx/articles/service-fabric-int.md
docs/docfx/articles/session-affinity.md
docs/docfx/articles/transforms.md

These `Introduced: preview3` tags are no longer relevant now that 1.0 has shipped. We may include some new ones for features added in the future, but expect them to reference full versions, not previews.

Remove doc Introduced tags

---

azure-pipelines.yml

- These don't contribute to the official artifacts, and if left running would be required to move to 1ES pools.
- The linux/mac runs will still run in public rolling CI and PRs.

Don't run linux/mac in official builds

---

docs/docfx/articles/config-files.md
docs/docfx/articles/config-providers.md
src/ReverseProxy/Configuration/IProxyConfig.cs
src/ReverseProxy/Management/ProxyConfigManager.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs
testassets/ReverseProxy.Config/Startup.cs
testassets/ReverseProxy.Config/appsettings.json

Fixes #979
Contributes to #368
Customers want to be able to do more advanced things with config like:
- Load it from multiple places: JSON, in memory, k8, etc.
- Be able to mix and match across those sources. E.g. routes are defined in memory and clusters in json.
Design:
- Multiple LoadFromX calls can now be made. No new APIs are needed, but we will want to ensure the existing ones behave as expected if called multiple times. I've only verified LoadFromConfig so far. Others might not make sense to call multiple times but could still be mixed and matched.
- The config manager will resolve all IProxyConfigProvider's from the DI container, concatenate their contents, run validation, and update the internal state.
- RouteConfig and ClusterConfig are the smallest units supported. Duplicates …

Support multiple configuration sources

---

src/Kubernetes.Controller/Converters/YarpIngressOptions.cs
src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/testassets/route-metadata/clusters.json
test/Kubernetes.Tests/testassets/route-metadata/ingress.yaml
test/Kubernetes.Tests/testassets/route-metadata/routes.json

Add support for Route Metadata in Kubernetes via annotations #1479.
A change similar to #1263.

Add support for Route Metadata in Kubernetes via annotations

---

src/ReverseProxy/Transforms/QueryTransformContext.cs
test/ReverseProxy.Tests/Transforms/QueryTransformContextTests.cs

This PR will change the query collection of `QueryTransformContext` to be case insensitive which will be consistent with ASP.NET.
This PR fixes the bug mentioned in issue: [1496](https://github.com/microsoft/reverse-proxy/issues/1496)

Changing QueryTransformContext query collection to be case insensitive

---

docs/docfx/articles/ab-testing.md
docs/docfx/articles/toc.yml
src/ReverseProxy/Management/IProxyStateLookup.cs
src/ReverseProxy/Management/IReverseProxyBuilderExtensions.cs
src/ReverseProxy/Management/ProxyConfigManager.cs
src/ReverseProxy/Model/HttpContextFeaturesExtensions.cs
src/ReverseProxy/SessionAffinity/AffinitizeTransform.cs
src/ReverseProxy/Utilities/NullableAttributes.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs
test/ReverseProxy.Tests/Model/HttpContextFeaturesExtensions.cs
testassets/ReverseProxy.Code/Startup.cs

Contributes to https://github.com/microsoft/reverse-proxy/issues/126#issuecomment-1024494147
This provides the minimal infrastructure necessary to build your own A/B testing or rolling upgrade system.
A) You can now directly look up routes and clusters
B) You can re-assign a request to a new cluster
That should allow a developer to provide their own custom middleware that examines requests, chooses a cluster, and assigns the request accordingly.
Note: Changing the cluster can cause some issues with Session Affinity if the two clusters have different affinity configurations, especially if it's enabled in one and disabled in the other. I've left this as a warning for now, not sure if anyone will need different settings across A/B clusters.

Add cluster access API, reassignment

---

docs/docfx/articles/config-files.md
docs/docfx/articles/session-affinity.md
samples/ReverseProxy.Config.Sample/appsettings.json
test/ReverseProxy.Tests/SessionAffinity/BaseSessionAffinityPolicyTests.cs
test/ReverseProxy.Tests/SessionAffinity/CookieSessionAffinityPolicyTests.cs
test/ReverseProxy.Tests/SessionAffinity/CustomHeaderSessionAffinityPolicyTests.cs

The name for `Return503ErrorAffinityFailurePolicy` in the documentation is incorrect. Actual policy name is picked from constants: 
[SessionAffinityConstants.cs](https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/SessionAffinity/SessionAffinityConstants.cs#L22). I've replaced incorrect name in the docs, samples and tests.
Also I've checked actual branches and issues and it does not seem to be fixed yet.
I'm still not sure which branch must be target my small PR ☹.

Fixed Return503Error affinity policy name

---

src/ReverseProxy/Management/ProxyConfigManager.cs
src/ReverseProxy/Model/ClusterState.cs
src/ReverseProxy/Model/RouteModel.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs

Fixes #1566
The `ClusterModel` is exposed on the `IReverseProxyFeature`, leading to out-of-sync information being presented to the user after destination updates. This change also updates the `ClusterState.Model` on destination changes.
We still avoid incrementing the `Revision` on destination-only changes to avoid re-creating the endpoint.

Update the cluster model on destination changes

---

docs/docfx/docfx.json

Turns the [API documentation list](https://microsoft.github.io/reverse-proxy/api/index.html) into a much more manageable and relevant data source (avoids all the k8s and SF code from showing up there).

Only add API documentation for released projects

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopyHttpContentTests.cs

Delay capturing body request until calling `SerializeToStreamAsync`. It allows to enable buferring in request transform.
Fixes #1473

Delay capturing body request

---

src/ReverseProxy/Health/DestinationHealthUpdater.cs

`ActiveDestinationHealthStateIsSet` has leading uppercase when logging the enum value. This makes the literal string states consistent with that.

Consistent casing in Destination Health logs

---

src/ReverseProxy/Management/ProxyConfigManager.cs

If the initial configuration load fails, `_configs` won't be initialized and `Dispose` hits a `NullReferenceException`.
Failure to load the config on startup is already a critical, non-recoverable error, this PR just removes the NRE from the stack trace.
Given that, I don't think it's needed to restart the official 1.1 RC build for this.
Hit during manual validation of #1596.

Avoid NRE from ProxyConfigManager if the initial load fails

---

docs/docfx/articles/header-guidelines.md

Just a tiny typo in x-http-method-override in the doc title.

Fix typo in "x-http-method-override"

---

docs/docfx/articles/config-providers.md

While going through the docs I spotted a few typos and I then used a grammar tool to fix the ones I didn't see.

docs: typos in config-providers

---

test/ReverseProxy.FunctionalTests/HttpForwarderCancellationTests.cs

It can also be a `TaskCanceledException`, which is derived from OCE.

Fix assert in cancellation test

---

docs/docfx/articles/config-providers.md

Backporting #1643 from `release/latest` to `main`

Backport #1643 to main

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Fixes #1628
`RequestTimedOut` is described as
> Timed out when trying to connect, send the request headers, or receive the response headers.
So a `ConnectTimeout` fits this existing description.
cc: @davidni

Classify a ConnectTimeout as RequestTimedOut

---

src/ReverseProxy/Routing/HeaderMatcher.cs
src/ReverseProxy/Routing/HeaderMatcherPolicy.cs
src/ReverseProxy/Routing/HeaderMetadata.cs
src/ReverseProxy/Routing/IHeaderMetadata.cs
src/ReverseProxy/Routing/IQueryParameterMetadata.cs
src/ReverseProxy/Routing/QueryParameterMatcher.cs
src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs
src/ReverseProxy/Routing/QueryParameterMetadata.cs
test/ReverseProxy.Tests/Routing/HeaderMatcherPolicyTests.cs
test/ReverseProxy.Tests/Routing/ProxyEndpointFactoryTests.cs
test/ReverseProxy.Tests/Routing/QueryMatcherPolicyTests.cs

Fixes #1494
Matching now treats multiple values as *OR*s. I.e. `Exact`/`Prefix` must match *any* of the request values.
`NotContains` means the value must *not match any* request header.
Values are further split based on the separator `,` (or `;` for `Cookie`). A single outer pair of quotes is also removed before matching.
This PR is generally slightly faster on simple (single-value) inputs, and (as expected) slower on multi-value ones.
Modes that may observe a perf degradation are `Exact` and `Prefix`.
I don't think the difference is prohibitive to the point that having an opt-out switch is needed.
Benchmark scenarios are defined [here](https://gist.github.com/MihaZupan/ccac2200ff7ba2f509060ee1a061e230#file-headerroutingbenchmark-cs-L30-L64).
| Method |         Scenario |      Mean | …

Add support for multi-value header routing

---

docs/docfx/articles/runtimes.md

Resolves #1563
I updated only .NET 6 features; I would add .NET 7 when the full list of features is ready.

Update doc supported .NET 6 runtime

---

src/ReverseProxy/Forwarder/StreamCopier.cs

Contributes to #1665 and #1657.
@Tratcher feel free to close this one if you think we need any more changes here.

Disable zero-byte-reads on 3.1 and 5.0

---

docs/docfx/articles/lets-encrypt.md
docs/docfx/articles/toc.yml
reverse-proxy.sln
samples/README.md
samples/ReverseProxy.LetsEncrypt.Sample/Program.cs
samples/ReverseProxy.LetsEncrypt.Sample/Properties/launchSettings.json
samples/ReverseProxy.LetsEncrypt.Sample/README.md
samples/ReverseProxy.LetsEncrypt.Sample/ReverseProxy.LetsEncrypt.Sample.csproj
samples/ReverseProxy.LetsEncrypt.Sample/Startup.cs
samples/ReverseProxy.LetsEncrypt.Sample/appsettings.json

Add Lets Encrypt sample and article

---

docs/operations/Release.md
eng/Versions.props

Contributes to #1676.
This enables producing non-preview final builds.

Update branding to rtw

---

docs/docfx/articles/getting-started.md

Getting Started guide has invalid JSON with a trailing comma. Verified in sample project and JSON lint.

Fix trailing comma in appsettings.json

---

README.md

Assuming most people want to try using the project over building/testing the repo itself.

Move getting started to the top of readme

---

docs/docfx/articles/config-providers.md
samples/ReverseProxy.Code.Sample/InMemoryConfigProvider.cs
src/Kubernetes.Controller/ConfigProvider/KubernetesConfigProvider.cs
test/ReverseProxy.FunctionalTests/Common/InMemoryConfigProvider.cs
test/ReverseProxy.Tests/Common/InMemoryConfigProvider.cs
testassets/ReverseProxy.Code/InMemoryConfigProvider.cs

Not sure if we care about this scenario (multiple concurrent `Update`s), but since we're considering exposing it (#1713) it seems worth doing.
For reference the issue is that multiple `Update` calls may read the same `oldConfig` and one of the new configurations will never be signaled. If the proxy picks up that config object, it will stop responding to config updates.

Fix race condition for concurrent Updates in InMemoryConfigProvider

---

src/ReverseProxy/Utilities/TlsFrameHelper.cs

Fixes #1613
See similar issue and PR in dotnet/runtime:
https://github.com/dotnet/runtime/issues/66781
https://github.com/dotnet/runtime/pull/66786

Fixed TlsHandshakeType enum label

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Matches the behavior used on the request side to only add the "Upgrade" header if the connection header contains an entry for it: https://github.com/microsoft/reverse-proxy/blob/94bd1273d223a37ab078a19d3173f5686543a68e/src/ReverseProxy/Forwarder/HttpForwarder.cs#L305-L323

Don't restore the upgrade header if there is no corresponding Connection entry

---

docs/docfx/articles/transforms.md

The example documentation produces the error `The proxy config is invalid. (Unknown transform: Append;QueryStringParameter)`.

Fix `QueryValueParameter` example

---

test/Kubernetes.Tests/IngressControllerTests.cs

The test was occasionally failing because of order of execution of the
program.

Fix flaky ReconciliationContinuesOnReconcilerError unit test

---

samples/KubernetesIngress.Sample/README.md

Looks like a copy/paste error in the docs for the yarp.ingress.kubernetes.io/backend-protocol annotation

Fix copy/paste error in docs

---

src/ReverseProxy/Model/HttpContextFeaturesExtensions.cs
test/ReverseProxy.Tests/Model/HttpContextFeaturesExtensions.cs

Adds an overload for ReassignProxyRequest that assigns both route and cluster when reassigning a proxy request.
See discussions in #1749 and #1752 for more info.

Overload ReassignProxyRequest to also accept a route update

---

samples/SampleServer/Controllers/WebSocketsController.cs
samples/SampleServer/Startup.cs
samples/SampleServer/wwwroot/index.html
src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs

#1770
The client expects the server to close the socket first. Kestrel will only close the underlying socket once YARP exits. YARP isn't exiting because it's still trying to read from the client. When a WebSocket response copy loop finishes gracefully YARP needs to cancel the request copy loop so we can quickly clean things up. Ignore any errors caused by this cancellation.
Merge #1774 first

Close WebSockets gracefully 

---

docs/docfx/articles/https-tls.md

Fixed a spelling mistake in the documentation

Spelling Typo in https-tls docs

---

src/ReverseProxy/Forwarder/HttpTransformer.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

Fix https://github.com/microsoft/reverse-proxy/issues/1762

Remove Content-Length: 0 on responses that don't allow bodies

---

src/ReverseProxy/Forwarder/ProtocolHelper.cs

Noticed this TODO item while looking through the sources. The mentioned aspnetcore issue was addressed nearly two years ago :smile:
Benchmarking indicates that the perf difference here is negligible, but this is definitely cleaner from a maintenance standpoint.

Use MediaTypeHeaderValue.MatchesMediaType for content type check

---

test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs

With a recent enough build of 7.0, this test is failing since the exception can now be an [`HttpProtocolException`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpProtocolException.cs).

Fix Except100Continue test for 7.0

---

src/ReverseProxy/Management/ReverseProxyServiceCollectionExtensions.cs
test/ReverseProxy.Tests/Forwarder/ReverseProxyServiceCollectionTests.cs

Fixes https://github.com/microsoft/reverse-proxy/issues/1799

Throw an exception in ConfigureHttpClient when custom IForwarderHttpClientFactory is added

---

src/Kubernetes.Controller/ConfigProvider/KubernetesConfigProvider.cs
src/ReverseProxy/Configuration/IConfigChangeListener.cs
src/ReverseProxy/Configuration/IProxyConfig.cs
src/ReverseProxy/Configuration/InMemoryConfigProvider.cs
src/ReverseProxy/Management/ProxyConfigManager.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs

Fix #1619
_From the original issue:_
"When dynamically applying loaded configuration (cf. https://microsoft.github.io/reverse-proxy/articles/config-providers.html) after the initial startup, any validation failure will be logged, then silenced.
We would need a way to get notified of both successful configuration changes and invalid configuration rejection."
This is an attempt to propagate whether or not the loaded configuration has been applied or not.

Expose IConfigChangeListener callback service

---

samples/KubernetesIngress.Sample/Combined/Dockerfile
samples/KubernetesIngress.Sample/Ingress/Dockerfile
samples/KubernetesIngress.Sample/Monitor/Dockerfile
samples/KubernetesIngress.Sample/backend/Dockerfile

https://github.com/dotnet/install-scripts/issues/308 has been fixed so this workaround shouldn't be needed anymore

Remove dotnet-install CRLF workaround

---

docs/docfx/docfx.csproj

Fixes #1859
A recent update of MSBuild seems to have broken a bunch of stuff, including docfx.
Some discussion on https://github.com/dotnet/docfx/issues/8097 and https://github.com/dotnet/docfx/issues/8136.
Docfx added a workaround https://github.com/dotnet/docfx/pull/8135 that is now released in `2.59.4`.
It solves the issue for me when testing locally.
> [22-09-07 10:52:17.669]Warning:[MetadataCommand.ExtractMetadata](D:/a/reverse-proxy/reverse-proxy/source/src/ReverseProxy/Yarp.ReverseProxy.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\a\reverse-proxy\reverse-proxy\source\src\ReverseProxy\Yarp.ReverseProxy.csproj' with message: Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.

Bump Docfx to 2.59.4

---

samples/KubernetesIngress.Sample/README.md
src/Kubernetes.Controller/Converters/YarpIngressOptions.cs
src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/testassets/route-headers/clusters.json
test/Kubernetes.Tests/testassets/route-headers/ingress.yaml
test/Kubernetes.Tests/testassets/route-headers/routes.json

read  RouteHeader from ingress annotations, key: `yarp.ingress.kubernetes.io/route-headers`

add Header-based canary routing via ingress annotations

---

samples/ReverseProxy.Metrics.Sample/Startup.cs
src/TelemetryConsumption/EventListenerService.cs
src/TelemetryConsumption/TelemetryConsumptionExtensions.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs

I am writing networking telemetry docs and it bothered me that we have very convenient helpers for `ITelemetryConsumer*`s, but nothing for `IMetricsConsumer<T>`.
So while you can write code like this for events:
```c#
services.AddTelemetryConsumer<MyTelemetryConsumer>();
```
you have to write this for metrics:
```c#
services.AddSingleton<IMetricsConsumer<SocketsMetrics>, MetricsConsumer>();
services.AddTelemetryListeners();
```
or even this if you implement multiple interfaces:
```c#
services.AddSingleton<MetricsConsumer>();
services.AddSingleton(services => (IMetricsConsumer<ForwarderMetrics>)services.GetRequiredService<MetricsConsumer>());
services.AddSingleton(services => (IMetricsConsumer<KestrelMetrics>)services.GetRequiredService<MetricsConsumer>());
services.AddSingleton(services …
```

Add AddMetricsConsumer helper to TelemetryConsumption

---

.config/tsaoptions.json
azure-pipelines.yml

- add a new weekly schedule to keep database and tools up to database
- add top-level parameter enabling CodeQL3000 in manual builds
- add CodeQL3000 variables
- add CodeQL3000 tasks
- not auto-injected because that happens only in builds of the default branch
- add tag indicating CodeQL3000 tasks did useful work
- ignore no-op task executions
- add a tsaoptions.json file
- cribbed values from eng/sdl-tsa-vars.config file
nits:
- disable auto-injection of build steps we or Arcade do explicitly
- remove irrelevant variables in test jobs

[main] Add CodeQL3000 to microsoft-reverse-proxy-official

---

.config/tsaoptions.json
azure-pipelines.yml

- backport of #1914
- add a new weekly schedule to keep database and tools up to database
- add top-level parameter enabling CodeQL3000 in manual builds
- add CodeQL3000 variables
- add CodeQL3000 tasks
- not auto-injected because that happens only in builds of the default branch
- add tag indicating CodeQL3000 tasks did useful work
- ignore no-op task executions
- add a tsaoptions.json file
- cribbed values from eng/sdl-tsa-vars.config file
also:
- backport #1843
- backport #1848
- switch to `-Svc` pools since this is a servicing branch
nits:
- disable auto-injection of build steps we or Arcade do explicitly
- remove irrelevant variables in test jobs

[release/1.0] Add CodeQL3000 to microsoft-reverse-proxy-official

---

.config/tsaoptions.json
azure-pipelines.yml

- backport of #1914
- add a new weekly schedule to keep database and tools up to database
- add top-level parameter enabling CodeQL3000 in manual builds
- add CodeQL3000 variables
- add CodeQL3000 tasks
- not auto-injected because that happens only in builds of the default branch
- add tag indicating CodeQL3000 tasks did useful work
- ignore no-op task executions
- add a tsaoptions.json file
- cribbed values from eng/sdl-tsa-vars.config file
also:
- backport #1843
- switch to `-Svc` pools since this is a servicing branch
nits:
- disable auto-injection of build steps we or Arcade do explicitly
- remove irrelevant variables in test jobs

[release/latest] Add CodeQL3000 to microsoft-reverse-proxy-official

---

samples/SampleServer/Controllers/WebSocketsController.cs
samples/SampleServer/wwwroot/index.html
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs

Forward port of #1773 into main. Contributes to #1770.
TODO: I'm seeing some failures in WebSocketTelemetryTests that didn't show up in the original PR, but are now showing up locally in both 1.1 and main. 🤷 
- I partially understand now. Before a server graceful disconnect presented as a client timeout. Now YARP cancels the reads and suppresses the error, causing the telemetry to report Unknown.
- The telemetry can track reads and know when read returns 0, but it can't know when the write stream is closed unless it tries to write to it.
The test changes should be backported to 1.1.

Close WebSockets gracefully

---

src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs

Backport of a reporting issue found when forward porting the rest of the fix: https://github.com/microsoft/reverse-proxy/pull/1790

Fix WebSocketCloseReason for suppressed error

---

docs/docfx/articles/transforms.md
samples/ReverseProxy.Auth.Sample/Startup.cs
samples/ReverseProxy.Auth.Sample/TokenService.cs
samples/ReverseProxy.Auth.Sample/Views/Account/Login.cshtml
samples/ReverseProxy.Transforms.Sample/MyTransformProvider.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/HttpTransformer.cs
src/ReverseProxy/Forwarder/RequestUtilities.cs
src/ReverseProxy/Transforms/Builder/StructuredTransformer.cs
src/ReverseProxy/Utilities/EventIds.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Fixes #1701 @leastprivilege 
If a request transform encounters a problem right now the only thing it can do is throw. A few customers have asked how to generate a response and exit gracefully. Response transforms can already do this by returning false to prevent us from proxying the body.
- https://github.com/microsoft/reverse-proxy/issues/1701
- https://github.com/microsoft/reverse-proxy/issues/1670
- https://github.com/microsoft/reverse-proxy/discussions/1724
`HttpTransformer.TransformRequestAsync` has a signature that can't return any additional information without an API breaking change. Instead, we can detect if a transform generated a response by checking HttpResponse.StatusCode or HasStarted. In this case we'll stop trying to proxy the request and exit gracefully. If someone had …

Enable request transforms to reject requests 

---

docs/docfx/articles/config-files.md
docs/docfx/articles/middleware.md
src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
src/ReverseProxy/Configuration/ConfigProvider/ConfigurationReadingExtensions.cs
src/ReverseProxy/Configuration/RouteConfig.cs
src/ReverseProxy/Limits/LimitsMiddleware.cs
src/ReverseProxy/Routing/ReverseProxyIEndpointRouteBuilderExtensions.cs
src/ReverseProxy/Utilities/EventIds.cs
test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Limits/LimitsMiddlewareTests.cs

Fixes #640
The servers all have a configurable MaxRequestBodySize limit that defaults to ~30MB. This can be overridden per request with a feature. The most common case is to raise it for certain endpoints that upload big files, or to disable it for streaming scenarios. Some scenarios automatically disable it like WebSockets or gRPC streaming. Others need to be configured.
There is .NET 8 work planned to centralize this into endpoint metadata and middleware, but we want to support this for 6 and 7 in the meantime. https://github.com/dotnet/aspnetcore/issues/40452

Make MaxRequestBodySize configurable 

---

src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/testassets/hostname-routing/routes.json
test/Kubernetes.Tests/testassets/multiple-hosts/clusters.json
test/Kubernetes.Tests/testassets/multiple-hosts/ingress.yaml
test/Kubernetes.Tests/testassets/multiple-hosts/routes.json
test/Kubernetes.Tests/testassets/multiple-ingresses/routes.json
test/Kubernetes.Tests/testassets/multiple-namespaces/routes.json

Include Host name in Yarp Route Id, when parsing Ingress Manifest Rules.
Fixes issue as described in #1950

Add support for addition of Multiple Host Domains to K8s Ingress Rules

---

src/Kubernetes.Controller/Caching/ICache.cs
src/Kubernetes.Controller/Caching/IngressCache.cs
src/Kubernetes.Controller/Services/Reconciler.cs
test/Kubernetes.Tests/IngressCacheTests.cs

There is currently a race condition in the loading of K8s resources through the resource informers. If the ingress resources load before the ingress classes, and they have an ingress class name specified, then they are not considered for config generation. Similarly, if you have your yarp ingress class defined as default, but ingresses load first, then they are also not considered because the controller is not yet aware of what the default controller should be.
This fix guarantees the ingress classes will be loaded first prior to loading all other resource types. Please let me know if you would like this done a different way, I am happy to make any changes to help see this contribution through.

Fix startup race condition in K8s IngressController

---

test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
test/ReverseProxy.FunctionalTests/DistributedTracingTests.cs
test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs
test/ReverseProxy.FunctionalTests/HeaderTests.cs
test/ReverseProxy.FunctionalTests/HttpForwarderCancellationTests.cs
test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs
test/ReverseProxy.FunctionalTests/PassiveHealthCheckTests.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs
test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs

I was adding new functional tests for H2WS (https://github.com/microsoft/reverse-proxy/issues/1375) but found the structure of the TestEnvironment difficult to add additional properties to due to the complex constructors. I've re-factored it to use properties instead.

Refactor functional test environment

---

docs/docfx/articles/dests-health-checks.md

In the example of FirstUnsuccessfulResponseHealthPolicy, there are following issues need to be address with the code:
1. public void RequestProxied function was provided parameters with wrong order
2. SetPassiveAsync is internal function
3. IProxyErrorFeature cannot be found, should be IForwarderErrorFeature

internal SetPassiveAsync can't be used

---

docs/docfx/articles/header-guidelines.md
src/ReverseProxy/Forwarder/RequestUtilities.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs

Fixes #1862
Strict-Transport-Security is a per-hop response header. Since we terminate TLS, we should not proxy this header.

Drop the Strict-Transport-Security response header 

---

test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs

Closes #1882
This ensures that the telemetry stream has been initialized before we start changing the clock.

Fix ConnectionClosed_BlameReliesOnCloseTimes test

---

docs/docfx/articles/direct-forwarding.md
docs/docfx/articles/http-client-config.md
samples/ReverseProxy.Direct.Sample/Startup.cs
src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs
testassets/ReverseProxy.Direct/Startup.cs

Set the default ConnectTimeout to a finite value

---

src/ReverseProxy/Forwarder/ForwarderRequestConfig.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/HttpTransformer.cs
src/ReverseProxy/Forwarder/IHttpForwarder.cs
src/ReverseProxy/Transforms/Builder/StructuredTransformer.cs
src/ReverseProxy/Transforms/RequestTransformContext.cs
src/ReverseProxy/Transforms/ResponseTrailersTransformContext.cs
src/ReverseProxy/Transforms/ResponseTransformContext.cs
src/ReverseProxy/Utilities/ActivityCancellationTokenSource.cs
test/ReverseProxy.Tests/Transforms/Builder/TransformBuilderTests.cs
test/ReverseProxy.Tests/Utilities/ActivityCancellationTokenSourceTests.cs

Fixes #1542
Some customers using IHttpForwarder directly have asked for the ability to pass their own cancellation token. Today they have to replace HttpContext.RequestAborted which can be error prone.
This uses a Default Interface Method to avoid a breaking change.

Enable direct cancellation for IHttpForwarder 

---

src/ReverseProxy/SessionAffinity/AffinitizeTransform.cs
src/ReverseProxy/SessionAffinity/ISessionAffinityPolicy.cs
src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs
test/ReverseProxy.Tests/SessionAffinity/AffinitizeTransformTests.cs
test/ReverseProxy.Tests/SessionAffinity/SessionAffinityMiddlewareTests.cs

Add async ISessionAffinityPolicy APIs

---

src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj

Brings back #941
This slipped through in #1642 when we rearranged all the k8s project files.
Contributes to #1995
I'll backport this to main as well.

Set IsPackable to false for the k8s project

---

azure-pipelines.yml
eng/Version.Details.xml
eng/Versions.props
eng/common/build.ps1
eng/common/init-tools-native.ps1
eng/common/sdk-task.ps1
eng/common/templates/job/execute-sdl.yml
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/jobs/source-build.yml
eng/common/templates/post-build/post-build.yml
eng/common/tools.ps1
global.json

#1995
These two changes are the only things where release/latest is ahead of main or rc1.
After this we should be able to force push the rc1 branch into release/latest.

Update release/2.0.0-rc1 with Arcade changes from release/latest

---

docs/docfx/articles/ab-testing.md
docs/docfx/articles/https-tls.md
docs/docfx/articles/middleware.md
docs/docfx/articles/runtimes.md

These 4 were the only ones the docfx build complained about.

Fix broken docs cross-links

---

docs/docfx/articles/direct-forwarding.md
samples/ReverseProxy.Direct.Sample/Startup.cs
src/ReverseProxy/Forwarder/ForwarderError.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/HttpTransformer.cs
src/ReverseProxy/Forwarder/RequestTransformer.cs
src/ReverseProxy/Transforms/Builder/StructuredTransformer.cs
src/ReverseProxy/Utilities/ActivityCancellationTokenSource.cs
test/ReverseProxy.Tests/Common/TestTrailersFeature.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs
test/ReverseProxy.Tests/Transforms/Builder/TransformBuilderTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTrailerRemoveTransformTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTrailerValueTransformTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTrailersAllowedTransformTests.cs
test/ReverseProxy.Tests/Transforms/ResponseTrailersTransformTests.cs
test/ReverseProxy.Tests/Utilities/ActivityCancellationTokenSourceTests.cs
testassets/ReverseProxy.Direct/Startup.cs

This PR does a few things:
- Marks `HttpTransformer` overloads without the `CancellationToken` as obsolete.
- Makes sure all scenarios work as expected with the built-in `StructuredTransformer` (you can call overloads with or without the CT and it'll work).
- Makes sure `HttpForwarder` always calls the overloads with the cancellation token.
- Moves request transform calls into the try/catch block with `HttpClient.SendAsync` so that any failures are reported in a similar manner. Also added `ForwarderError.RequestCreation` in case the exception is not related to cancellation.
- Switched the error reported if the manual CT is signaled to `RequestCanceled` (was `RequestTimedOut`).
- Added a bunch of tests for the above.

Fix HttpTransformer-related issues

---

docs/docfx/articles/transforms.md

Replace TransformValidationContext with TransformRouteValidationContext in TransformFactory example. I noticed it was wrong when I copied the code into a project I"m working on. It is correct in the sample at https://github.com/microsoft/reverse-proxy/blob/main/samples/ReverseProxy.Transforms.Sample/MyTransformFactory.cs

fix small mistake in transform documentation

---

test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs

Failed in #2030 with a non-helpful error.

Add ignored exception logging for failing WS telemetry test

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs

We determine whether to report `Request` vs `RequestCreation` based on whether `destinationRequest is null` or not.
If an exception was thrown by the request transform for the downgrade request, it would be reported as `Request` instead of `RequestCreation`.

Fix edge-case error attribution bug on WS downgrade

---

azure-pipelines.yml

- import the variable template
- use the two variables it provides wherever we name the pool
- future release branches will now automatically switch to the -Svc pools

Use Arcade's pool-providers.yml

---

src/ReverseProxy/Forwarder/HttpForwarder.cs

Fixes #2025 
Warning level should be for any unsuccessful proxying, things YARP is able to recover from - e.g. destination going out, client-side problems with network- see [list in code](https://github.com/microsoft/reverse-proxy/blob/03a4d6a91b9b65f90e8c616bebc77e1338bec81a/src/ReverseProxy/Forwarder/HttpForwarder.cs#L1063-L1081).

Update log level to warning for unsuccessful proxying

---

src/Kubernetes.Controller/Protocol/Receiver.cs
src/Kubernetes.Controller/Protocol/ReceiverOptions.cs

For #1926 , make Receiver's HttpClient instance from ReceiverOptions.

Make Receiver's HttpClient extensible

---

src/ReverseProxy/LoadBalancing/PowerOfTwoChoicesLoadBalancingPolicy.cs
test/ReverseProxy.Tests/LoadBalancing/LoadBalancingPoliciesTests.cs

The two calls to `Random.Next` may return the same index, so the comparison happens against the same destination. This behavior compromises the worst case protection this algorithm has because it might only use the worst destination, not offering opportunity of a better one. The fewer destinations we have, the more prominent this issue becomes.

Fix an issue where destinations are compared against themselves

---

src/TelemetryConsumption/EventListenerService.cs

Fixes #2102
I confirmed manually that this does resolve the issue. I'm not sure we can have a reliable test for this without tooling like `RemoteExecutor` since the EventSources and listeners are all global in a given process.

Workaround EventListener bug when consuming metrics

---

src/ReverseProxy/Forwarder/HttpForwarder.cs

Fix extended connect check condition

---

samples/KubernetesIngress.Sample/README.md

I recently tried using the Kubernetes Ingress controller pieces from this repository. While trying out some things I noticed that the doc wasn't correct on how metadata should be configured using annotations on the Ingress. If I did it the way the docs said I got the following error:
```
warn: Yarp.Kubernetes.Controller.Services.Reconciler[0]
Uncaught exception occured while reconciling ingress default/minimal-ingress
(Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected 'MappingStart', got 'SequenceStart' (at Line: 1, Col: 1, Idx: 0).
```
After removing the dashes from the annotation it worked correctly.

Fix docs on route metadata

---

test/ReverseProxy.FunctionalTests/HeaderTests.cs

Hit in #2122
This condition doesn't add value to the test and is also wrong in a race - the thread pool is free to run the HttpClient continuations first, before completing the `destinationTask`.

Remove erroneous test assert

---

src/Kubernetes.Controller/Management/KubernetesReverseProxyServiceCollectionExtensions.cs
src/TelemetryConsumption/TelemetryConsumptionExtensions.cs
src/TelemetryConsumption/Yarp.Telemetry.Consumption.csproj

Also fix a simple warning in Yarp.Kubernetes.Controller. The rest of the warnings in this project will be addressed in https://github.com/microsoft/reverse-proxy/issues/2145.
Follow up to https://github.com/microsoft/reverse-proxy/pull/2144#issuecomment-1561269092

Enable AOT compatibility for Yarp.Telemetry.Consumption

---

samples/ReverseProxy.Config.Sample/README.md

Match readme instructions to the associated appsetting.json file values and fix broken link to HttpClient configuration

Update ReverseProxy.Config.Sample README.md, fix links

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/StreamCopier.cs
src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopierTests.cs
test/ReverseProxy.Tests/Forwarder/StreamCopyHttpContentTests.cs

Passive health checks rely on ForwarderError's reported by HttpForwarder to determine if the client, destination, or proxy was to blame for the failure. These are some improvements to how blame is attributed based on different error conditions.

Forwarder blame improvements

---

docs/docfx/articles/dests-health-checks.md
src/ReverseProxy/Configuration/ConfigValidator.cs
src/ReverseProxy/Health/ClusterDestinationsUpdater.cs
test/ReverseProxy.FunctionalTests/PassiveHealthCheckTests.cs

The current default policy is HealthyOrUnknown, excluding unhealthy endpoints and returning a 503 when none are available.
Health is only checked periodically so a destination may have recovered before the next check. In the case that we don't know of any healthy destinations it's preferable to at least try proxying to a potentially unhealthy one, the request may fail either way. This will also give passive health checks more ongoing data.

Change default policy to HealthyOrPanic

---

docs/docfx/articles/transforms.md

Typo in transform actions for XForwarded transforms

Typo in documentation for transform actions (XForwarded)

---

.github/workflows/backport.yml

Copied from https://github.com/dotnet/runtime/blob/main/.github/workflows/backport.yml and removed most of the comment that doesn't apply here

Add backport GitHub Action

---

src/ReverseProxy/Model/ClusterState.cs
src/ReverseProxy/Model/DestinationState.cs

This addresses two open issues, #2142 and #1792, related to difficulties in unit testing custom middleware due to the inability to initialize/modify ClusterState and DestinationState.
The `ClusterState` and `DestinationState` constructors are now overloaded to accept additional parameters, which enables better unit testing when updating the `ReverseProxyFeature` via `HttpContextFeaturesExtensions`. 
However it's worth noting that lifting these restrictions may allow the user to set the state in the `ReverseProxyFeature` that may potentially cause unintended side effects. Once I started diving deeper into the code, it seemed that there is some level of dependency on the immutable design, as there is logic related to making the state eventually consistent; I believe that's why there is some …

Overload constructors for ClusterState and DestinationState to enable unit testing

---

src/ReverseProxy/Forwarder/HttpForwarder.cs

As agreed in [issue](https://github.com/microsoft/reverse-proxy/issues/2194) I've changed `no-streaming` flag to empty string when logging request that is not an gRPC request.

Changed streaming flag to empty string when logging no gRPC request

---

src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/Yarp.Kubernetes.Tests.csproj
test/Kubernetes.Tests/testassets/external-name-ingress/clusters.json
test/Kubernetes.Tests/testassets/external-name-ingress/ingress.yaml
test/Kubernetes.Tests/testassets/external-name-ingress/routes.json

Add support for external names to Kubernetes Controller

---

src/ReverseProxy/Management/ProxyConfigManager.cs
src/ReverseProxy/ServiceDiscovery/DnsDestinationResolver.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs

When an exception is thrown from `IDestinationResolver.ResolveDestinationsAsync`, we should catch the exception and rethrow it with context, such as which cluster failed resolution and, if possible, which destination failed to be resolved.

Improve diagnostics for IDestinationResolver exceptions

---

samples/ReverseProxy.Auth.Sample/Startup.cs
src/ReverseProxy/Routing/DirectForwardingIEndpointRouteBuilderExtensions.cs
src/ReverseProxy/Transforms/PathRouteValuesTransform.cs
src/ReverseProxy/Transforms/PathTransformExtensions.cs
src/ReverseProxy/Utilities/StringSyntaxAttribute.cs

* Add internal StringSyntaxAttribute to remove `#ifdefs`
* Add route string syntax to a few more places
After:

Improve route string syntax usage

---

docs/docfx/articles/config-files.md
docs/docfx/articles/http-client-config.md
samples/ReverseProxy.Config.Sample/appsettings.json
src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
src/ReverseProxy/Configuration/ConfigValidator.cs
src/ReverseProxy/Configuration/HttpClientConfig.cs
src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs
test/ReverseProxy.Tests/Configuration/ClusterConfigTests.cs
test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Configuration/ConfigValidatorTests.cs
test/ReverseProxy.Tests/Configuration/HttpClientConfigTests.cs
test/ReverseProxy.Tests/Forwarder/ForwarderHttpClientFactoryTests.cs
test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs

This change intends to allow consumers to be able to choose tolerance for non-default (non-ASCII) encoding of Response headers for forwarded requests by leveraging [`SocketsHttpHandler.ResponseHeaderEncodingSelector`](https://docs.microsoft.com/dotnet/api/system.net.http.socketshttphandler.responseheaderencodingselector). The idea is to provide something similar to the existing [`HttpClientConfig.RequestHeaderEncoding`](https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Configuration.HttpClientConfig.html#Yarp_ReverseProxy_Configuration_HttpClientConfig_RequestHeaderEncoding) property via a new `HttpClientConfig.ResponseHeaderEncoding` property.
Hopefully, this helps close https://github.com/microsoft/reverse-proxy/issues/1346 and helps simplify solution for …

💡feat: allow for simpler override of Response header encoding of Forwarded Requests

---

src/ReverseProxy/Routing/HeaderMatcherPolicy.cs
src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs
test/ReverseProxy.Tests/Routing/HeaderMatcherPolicyTests.cs
test/ReverseProxy.Tests/Routing/QueryMatcherPolicyTests.cs

fixes #2260
Currently the NotContains modes for both Header and QueryParameter matches do not match correctly when the value of the header/query is empty or if the key does not exist entirely. 
Updated the match logic to the below (assuming any non-empty request values match the value specified by the route):
| Type | Mode | RequestKey | RequestValue | CurrentMatch | ExpectedMatch |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Header/QueryParam | NotContains | None | - | No | **Yes** |
| Header/QueryParam | NotContains | Exists | Empty | No | **Yes** |
| Header/QueryParam | NotContains | Exists | NonEmpty | No | No |

Update NotContains match mode for Header and QueryParameters to support missing/empty values

---

src/ReverseProxy/Forwarder/RequestUtilities.cs
src/ReverseProxy/Transforms/RequestHeaderForwardedTransform.cs
src/ReverseProxy/Utilities/SkipLocalsInit.cs
src/ReverseProxy/Utilities/ValueStringBuilder.cs

Same idea (and therefore similar numbers) as https://github.com/dotnet/aspnetcore/pull/49117.
While I was touching the code, I also added support for using a `stackalloc`ed buffer with `ValueStringBuilder` now that we're targeting TFMs that can always use `SkipLocalsInit`.
Also removed the `if (count == value.Length && !requiresEscaping)` path that's unreachable in our case (it's reachable in `PathString` because there we detect percent-encoded sequences and avoid re-encoding them).

Use SearchValues in `RequestUtilities.EncodePath`

---

src/TelemetryConsumption/Http/HttpEventListenerService.cs
src/TelemetryConsumption/Http/HttpMetrics.cs
src/TelemetryConsumption/Http/IHttpTelemetryConsumer.cs
src/TelemetryConsumption/Sockets/SocketsEventListenerService.cs
src/TelemetryConsumption/Sockets/SocketsMetrics.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs

Adds overloads for existing events with new parameters (implemented as DIMs that forward to the existing ones), and new events/metrics.

React to runtime EventSource changes

---

docs/docfx/articles/header-guidelines.md
eng/Versions.props
src/ReverseProxy/Configuration/ConfigValidator.cs
src/ReverseProxy/Forwarder/RequestUtilities.cs
src/ReverseProxy/Health/ActiveHealthCheckMonitor.cs
src/ReverseProxy/Health/ClusterDestinationsUpdater.cs
src/ReverseProxy/Health/PassiveHealthCheckMiddleware.cs
src/ReverseProxy/LoadBalancing/LoadBalancingMiddleware.cs
src/ReverseProxy/SessionAffinity/AffinitizeTransformProvider.cs
src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs
src/ReverseProxy/Transforms/RequestHeadersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseHeadersAllowedTransform.cs
src/ReverseProxy/Transforms/ResponseTrailersAllowedTransform.cs
src/ReverseProxy/Utilities/ServiceLookupHelper.cs
src/ReverseProxy/Yarp.ReverseProxy.csproj

Saves us a few ns for each header.

Use frozen collections

---

src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj

Fix #2134
This will enable the package creation only for non rtw build, meaning that the NuGet will be created for nightly and preview builds.

Set IsPackable to true for the k8s project on non rtw builds

---

docs/DailyBuilds.md

Fix #2134
Add reference to the .NET Libraries Transport Daily NuGet feed for the Yarp.Kubernetes.Controller package.

Add NuGet feed to get daily builds of  Yarp.Kubernetes.Controller package.

---

src/ReverseProxy/Transforms/RequestTransformContext.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs
test/ReverseProxy.Tests/Transforms/DestinationPrefixTransformTests.cs

Make RequestTransformContext.DestinationPrefix read-write

---

src/ReverseProxy/Configuration/ConfigValidator.cs
test/ReverseProxy.Tests/Configuration/ConfigValidatorTests.cs

Debugging during a test run I can see that `_rateLimiterPolicyProvider.GetPolicyAsync(rateLimiterPolicyName)` always returns null for the values `default` or `disable`, and the reason seems to be that the collection the method is reading from is empty - should it contain some default policies?

failing tests for rate limiter policy validation when 'default' or 'disable' used

---

docs/docfx/articles/timeouts.md
docs/docfx/articles/toc.yml
docs/docfx/articles/websockets.md
samples/ReverseProxy.Minimal.Sample/Program.cs
src/Kubernetes.Controller/Converters/YarpIngressOptions.cs
src/Kubernetes.Controller/Converters/YarpParser.cs
src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
src/ReverseProxy/Configuration/ConfigValidator.cs
src/ReverseProxy/Configuration/RouteConfig.cs
src/ReverseProxy/Configuration/TimeoutPolicyConstants.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Model/ProxyPipelineInitializerMiddleware.cs
src/ReverseProxy/Routing/ProxyEndpointFactory.cs
src/ReverseProxy/Utilities/EventIds.cs
test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Configuration/ConfigValidatorTests.cs
test/ReverseProxy.Tests/Configuration/RouteConfigTests.cs
test/ReverseProxy.Tests/Model/ProxyPipelineInitializerMiddlewareTests.cs
test/ReverseProxy.Tests/Routing/ProxyEndpointFactoryTests.cs
testassets/ReverseProxy.Code/ReverseProxy.Code.csproj
testassets/ReverseProxy.Code/Startup.cs
testassets/TestServer/Controllers/HttpController.cs

Fixes #2074 by exposing config that integrates with the new timeout middleware. This is a nearly identical clone of the Cors feature.

Timeout integration

---

src/ReverseProxy/Forwarder/ForwarderError.cs
src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketCloseReason.cs
src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

This addresses outstanding feedback from @mihazupan about the error reporting changes in #2167. The intent was to more correctly attribute blame for disconnects to something caused by the client or destination. For ActivityTimeouts the blame would go to whoever we were currently expecting data from. However, in the WebSocket case we may be expecting data in both ways all the time, and an ActivityTimeout can be considered a no-blame situation that deserves separate consideration.
I'm not sure if the same consideration should apply to gRPC/streaming.

Clarify websocket activity failure

---

docs/operations/Branching.md

The step "Update the branch to use 1ES servicing pools" isn't needed anymore since it's [handled automatically]( https://github.com/microsoft/reverse-proxy/blob/main/eng/common/templates/job/source-build.yml) now.

Update branching doc

---

docs/docfx/articles/authn-authz.md

Fixed the spelling from kerbereos to kerberos

Fixed spelling from kerbereos to kerberos

---

src/TelemetryConsumption/Kestrel/IKestrelTelemetryConsumer.cs
src/TelemetryConsumption/Kestrel/KestrelEventListenerService.cs
test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs

Adding [Connection Start ](https://github.com/dotnet/aspnetcore/blob/4b7810723c27d47cc982055c6615cccf664e2980/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelEventSource.cs#L73C20-L73C20) and [Connection Stop](https://github.com/dotnet/aspnetcore/blob/4b7810723c27d47cc982055c6615cccf664e2980/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelEventSource.cs#L91C13-L91C17) events

Adding Kestrel connection start/stop events

---

docs/docfx/articles/getting-started.md
docs/docfx/toc.yml

Fix #2345
Update docs to talk about dotnet 8 and yarp 2.1.0

Fix 2.1 docs

---

docs/docfx/articles/transforms.md

The current example is throwing the following exception:
```
System.AggregateException: The proxy config is invalid. (Unexpected value for X-Forwarded: proto,host,for,prefix. Expected one of ForwardedTransformActions) (Unexpected value for Prefix: X-Forwarded-. Expected one of ForwardedTransformActions) (The transform contains more parameters than expected: Append;Prefix;X-Forwarded)
---> System.ArgumentException: Unexpected value for X-Forwarded: proto,host,for,prefix. Expected one of ForwardedTransformActions
```

Fix Transforms documentation

---

docs/docfx/articles/distributed-tracing.md

See #2394 : Docs don't give a generic OTel example and don't explain the need to include AddHttpClientInstrumentation for this to work. (This is obscured because Azure Monitor/App Insights do this for you automatically but if you're doing vanilla OTel, it's on you.)

Add generic Otel distributed tracing instructions

---

docs/docfx/articles/load-balancing.md

small fix to make the csharp example code compile in the load balancing page

fix csharp example in load balancing page

---

src/TelemetryConsumption/Http/HttpEventListenerService.cs

This assert was randomly firing during local test runs for me. While the base `EventListenerService` doesn't opt-in to the `RequestFailedDetailed` keyword, a different event listener somewhere else may (e.g. VS diagnostic tools).
The product code is clearly doing the right checks here:
https://github.com/dotnet/runtime/blob/51b51bffbb4733a50c93a39f047b29ff424494d9/src/libraries/System.Net.Http/src/System/Net/Http/HttpTelemetry.cs#L76-L84
so I don't think we should care about this assert in YARP.

Delete debug assert in HttpEventListenerService

---

src/ReverseProxy/Health/ConsecutiveFailuresHealthPolicy.cs
test/ReverseProxy.Tests/Health/ConsecutiveFailuresHealthPolicyTests.cs

Fixes #2079 
~This fix is sort of a hack, but does not add any additional book keeping or change the health model while still yielding the desired behavior.~
~By simply initializing the failure count to the failure threshold, the first health probe will either keep the destination unhealthy, or it will swap to healthy just like before.~
Use the destination's previous state to inform the next state if we are below the failure theshold. This will prevent new destinations with slower server startup times from erroneously tranisitioning into healthy temporarily until the unhealthy threshold is eventually reached.
- Destinations with a state of `Unknown` will continue to be unknown until either the failure threshold is reached (=> Unhealthy) or a successful probe occurs (=> Healthy). This …

Do not transition servers into the healthy state until at least one healthy probe is detected.

---

src/ReverseProxy/Delegation/HttpSysDelegator.cs
src/ReverseProxy/Utilities/EventIds.cs

This PR fixes #2425 by detaching and attempting to re-attach to destination queues when an ERROR_OBJECT_NO_LONGER_EXISTS  error is received when attempting to delegate requests.

Update HttpSysDelegator to support detaching from and re-initializing queues when the http.sys queue no longer exists

---

src/ReverseProxy/Routing/HeaderMatcherPolicy.cs
test/ReverseProxy.Tests/Routing/HeaderMatcherPolicyTests.cs

Currently **Exists** and **NotExists** are the same when value is empty. Headers with empty values have no semantic meaning in HTTP. So I updated NotExists with empty value to true. This will go against the current behavior by design. 
Feel free to post any comments or suggestions. Initial discussion is here https://github.com/microsoft/reverse-proxy/pull/2258#discussion_r1335320211

Update notExists to true when value is empty

---

docs/docfx/articles/config-files.md
docs/docfx/articles/dests-health-checks.md
src/ReverseProxy/Configuration/ActiveHealthCheckConfig.cs
src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
src/ReverseProxy/Health/DefaultProbingRequestFactory.cs
test/ReverseProxy.Tests/Configuration/ActiveHealthCheckConfigTests.cs
test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Health/DefaultProbingRequestFactoryTests.cs

fixes #2420 
An attempt at allowing query strings in health probes.
If a query is specified both on the probe address and the probe path, the probe path wins.

Allow for using query strings in DefaultProbingRequestFactory.

---

docs/docfx/articles/direct-forwarding.md
docs/docfx/articles/http-client-config.md
samples/ReverseProxy.Direct.Sample/Program.cs
src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs
testassets/ReverseProxy.Direct/Program.cs

Use consistent handler defaults in docs and samples

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/SessionAffinity/BaseEncryptedSessionAffinityPolicy.cs
src/ReverseProxy/SessionAffinity/BaseHashCookieSessionAffinityPolicy.cs
src/ReverseProxy/SessionAffinity/ISessionAffinityPolicy.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Closes #2317
We'll call `TransformResponseAsync` with a null `proxyResponse` as part of error handling to give transforms a chance to always run.
If they end up throwing a cancellation exception there's no point in us propagating it out given we're about to report a more specific error anyway.

Ignore response transform OCEs that occur during error handling

---

docs/docfx/articles/authn-authz.md
docs/docfx/articles/config-files.md
docs/docfx/articles/cors.md
docs/docfx/articles/dests-health-checks.md
docs/docfx/articles/http-client-config.md
docs/docfx/articles/httpsys-delegation.md
docs/docfx/articles/load-balancing.md
docs/docfx/articles/rate-limiting.md
docs/docfx/articles/session-affinity.md
docs/docfx/articles/timeouts.md
docs/docfx/articles/transforms.md
samples/ReverseProxy.Auth.Sample/appsettings.json
samples/ReverseProxy.Direct.Sample/appsettings.json
testassets/ReverseProxy.Config/appsettings.json

Backport of #2457 from release/latest to main

Backport #2457 docs changes

---

azure-pipelines.yml

Backport of #2464 to release/2.1

[release/2.1] Remove CodeQL scheduled runs

---

test/ReverseProxy.FunctionalTests/PassiveHealthCheckTests.cs

Saw this being noisy in CI a few times.
The destinations will be updated in the background, a simple `Task.Yield` isn't a reliable way to avoid the race condition.

Fix race condition in passive health test

---

src/ReverseProxy/Utilities/ActivityCancellationTokenSource.cs

We can avoid updating the timer if we've already done so in the past few ms.
Improves RPS on the basic h1-h1 scenario by about 2 %.

Reduce the overhead of updating the activity timeout timer

---

src/ReverseProxy/Delegation/HttpSysDelegator.cs

Update queue get/create/update logic in HttpSysDelegator.AddOrUpdateRules to avoid GC timing bug

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Utilities/EventIds.cs
test/ReverseProxy.Tests/Common/TestEventListener.cs
test/ReverseProxy.Tests/Common/TestLogger.cs
test/ReverseProxy.Tests/Common/TestLoggerProvider.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Fixes #2195
This moves `RequestCanceled`, `RequestBodyCanceled` and `UpgradeRequestCanceled` to a debug-level log.
The only thing I'm not sure about is whether `ForwardingRequestCancelled` is the right name for it in case we decide to switch more errors to it in the future.
Most of the change is switching error tests to use a shared helper that now also asserts that the error was logged.

Move request cancellations to a separate log

---

src/ReverseProxy/Model/ProxyPipelineInitializerMiddleware.cs
test/ReverseProxy.Tests/Model/ProxyPipelineInitializerMiddlewareTests.cs

Fixes #2404
We now also detect if the debugger is attached, or if the timeout policy was configured with an infinite timeout.

Improve UseRequestTimeouts validation

---

src/ReverseProxy/Transforms/ForwardedTransformExtensions.cs

Add contextual doc comments indicating that using `AddForwarded` or `AddXForwarded` header transforms will remove the other from the `RequestTransforms` when either is enabled. Without the comments, this may seem to be an unexpected behavior without reading the source code of the extension methods to understand the effect each method has on the other at runtime.

Forwarded Header Transforms Doc Comments

---

test/ReverseProxy.FunctionalTests/Yarp.ReverseProxy.FunctionalTests.csproj
test/ReverseProxy.Tests/Yarp.ReverseProxy.Tests.csproj
testassets/BenchmarkApp/BenchmarkApp.csproj

This fixes the build failure in #2579
https://learn.microsoft.com/en-gb/dotnet/fundamentals/syslib-diagnostics/syslib0057 suggests new ways to load certs, which are only available with .NET 9.
Since we can't use that yet on older platforms, I'm just suppressing the analyzer in our tests.

Suppress SYSLIB0057 in tests

---

src/ReverseProxy/Forwarder/HttpForwarder.cs

There's no reason for this to be a separate helper anymore, the edge case it was handling doesn't exist anymore since .NET 5.
We can inline it and save the allocation.

Avoid an async state machine allocation from CopyResponseBodyAsync

---

src/ReverseProxy/Configuration/RouteConfig.cs

Documents https://github.com/microsoft/reverse-proxy/issues/2533#issuecomment-2291912701
> The MaxRequestBodySize set via YARP configuration applies to the request as it's being processed by YARP. It does not apply in any previous middleware you set during MapReverseProxy.
In your case, if you already read the whole body before a limit has been set, it won't be enforced later on since you're not reading from the request anymore (just from the already-buffered copy).

Document that MaxRequestBodySize only applies to the forwarder

---

docs/docfx/articles/timeouts.md

Timeouts came up a couple of times in issues/discussions and this point isn't obvious to someone testing out their YARP config, maybe this will help.

Document that request timeouts are disabled when running under a debugger

---

src/TelemetryConsumption/WebSockets/WebSocketCloseReason.cs
test/ReverseProxy.FunctionalTests/TelemetryEnumTests.cs

The public copy of `WebSocketCloseReason` we expose from the telemetry package was missing the `ActivityTimeout` entry.

Fix mismatched internal/public enum copies

---

eng/Versions.props

Bump version in main to 2.3.0 preview 1

---

Directory.Build.props

Unblocks #2656 #2657 #2661
Until we drop 7.0, we have to suppress the `NETSDK1138: The target framework is out of support` warning.

Allow building EOL TFMs for .NET 7.0

---

Directory.Build.props

Backport of #2658 to release/2.1
cc: @MihaZupan

[release/2.1] Allow building EOL TFMs for .NET 7.0

---

Directory.Build.props

Backport of #2658 to release/2.2
cc: @MihaZupan

[release/2.2] Allow building EOL TFMs for .NET 7.0

---

src/ReverseProxy/Delegation/DummyHttpSysDelegator.cs
src/ReverseProxy/Management/ReverseProxyServiceCollectionExtensions.cs

Workaround https://github.com/dotnet/aspnetcore/issues/59166
Closes #2652

Workaround broken .NET 9.0 HttpSys linux packages

---

src/ReverseProxy/Delegation/HttpSysDelegator.cs
src/ReverseProxy/Utilities/EventIds.cs

This PR has two changes:
1. Added logic to retry delegation when an ObjectDisposedException happens when delegating
#2426 added support to detach from an existing queue when ERROR_OBJECT_NO_LONGER_EXISTS happens due to the owning process detaching from the queue. This works but there exists a race condition where other requests might have already obtained the old handle before we re-initialized and then they get an ObjectDisposedException when trying to use the old handle. Now we retry this error so the request will obtain the new handle and retry the delegation.
2. Added an ID to the DelegationQueueState (which holds the current handle to the queue) and included that ID in most existing logs.
We've seen some odd behavior with IIS and queue management around iisreset. With multiple …

Some improvements to HttpSysDelegator logging and retry logic

---

test/ReverseProxy.Tests/Utilities/ActivityCancellationTokenSourceTests.cs

Saw it fail once in CI in #2685
The pool is backed by a queue, so retrying is meaningless here.

Make the ActivityCTS test more reliable

---

docs/docfx/docfx.csproj
eng/Versions.props
samples/KubernetesIngress.Sample/Combined/Yarp.Kubernetes.IngressController.csproj
samples/KubernetesIngress.Sample/Ingress/Yarp.Kubernetes.Ingress.csproj
samples/KubernetesIngress.Sample/Monitor/Yarp.Kubernetes.Monitor.csproj
samples/Prometheus/ReverseProxy.Metrics-Prometheus.Sample/ReverseProxy.Metrics.Prometheus.Sample.csproj
samples/ReverseProxy.LetsEncrypt.Sample/ReverseProxy.LetsEncrypt.Sample.csproj
src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj
test/Kubernetes.Tests/Yarp.Kubernetes.Tests.csproj
test/ReverseProxy.Tests/Yarp.ReverseProxy.Tests.csproj
test/Tests.Common/Yarp.Tests.Common.csproj
testassets/BenchmarkApp/BenchmarkApp.csproj

Moved all packages to use centrally-managed versions.
Bumped `KubernetesClient` to the latest version (15.0.1).
Fixes #2689

Update dependency package versions

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

From https://github.com/microsoft/reverse-proxy/issues/2721#:~:text=free%20to%20rewind.-,Can%20I%20also%20ask%20you%20what%20kind%20of%20features%20will%20break%20if%20I%20replace%20the%20content%3F,-If%20you%20look
> Can I also ask you what kind of features will break if I replace the content?
If you look at https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/HttpForwarder.cs you can search for `requestContent`.
A few examples:
- Error handling will be wrong (reported `ForwarderError`, proxy's response status code)
- [`ContentTransferring`](https://github.com/microsoft/reverse-proxy/blob/73283c06363b581b776267a8fa36f4d4233888d9/src/TelemetryConsumption/Forwarder/IForwarderTelemetryConsumer.cs#L42-L63) telemetry will not be emitted
- We use state on the custom …

Throw if a request transform overrides the request HttpContent

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
test/ReverseProxy.FunctionalTests/WebSocketTests.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

When we added HTTP/2 WebSocket support, the intention behind version selection was that we would match `SocketsHttpHandler`/`ClientWebSocket` behavior.
When the user specified `Version=2.0, Policy=RequestVersionOrHigher`, we should be attempting HTTP/2 WebSockets, regardless of whether the destination is using https or not.
Currently, we'll use HTTP/1.1 instead, which goes against the specified policy.
Aside from violating the configured policy, the current behavior is problematic when the backend service only supports HTTP/2. Instead of using H2 as requested, we'll downgrade the H1, and all requests will fail.
This change makes YARP strictly follow the version policy. If the user told us not to use HTTP/1.X, we simply shouldn't.
If the backend server happens to only support HTTP/1.X, …

Always enforce HttpVersionPolicy on WebSocket version negotiation

---

eng/Versions.props

The entry got duplicated in #2710.
The arcade update that was just merged should have ran into build errors, but we were using the older version of `Microsoft.DotNet.XUnitExtensions` due to the duplication.
Using the new version is blocked on the same issue as #2762 and #2764.

Remove duplicate MicrosoftDotNetXUnitExtensionsPackageVersion definition

---

YARP.sln
eng/Versions.props
samples/ReverseProxy.Config.Sample/appsettings.json
samples/ReverseProxy.Transforms.Sample/appsettings.json
src/Common/Package.targets
src/Directory.Build.props
src/ReverseProxy/Configuration/PassiveHealthCheckConfig.cs
src/ReverseProxy/Configuration/RouteHeader.cs
src/ReverseProxy/Configuration/SessionAffinityConfig.cs
src/ReverseProxy/ConfigurationSchema.json
src/ReverseProxy/Forwarder/ForwarderRequestConfig.cs
test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
test/ReverseProxy.Tests/Yarp.ReverseProxy.Tests.csproj
testassets/ReverseProxy.Config/appsettings.json

Closes #1350
The intention here is to make editing the config much easier without just copy-pasting everything, it's a non-goal that it will catch every possible validation error that may be raised at runtime.
For example I've added Regex validations to some items that can catch a superset of what's actually allowed.
Initial version created by Sam
Here's the diff since then https://github.com/MihaZupan/yarp/compare/d4f177d3828970f71a48246ee84a62b42ba9c0df..json-schema?w=1#diff-fa5250031a03ad88202dff86f92ad41cc9036352784ccb1b902250d55309b9a7

Add a Json schema for YARP configuration

---

src/ReverseProxy/Forwarder/HttpForwarder.cs
src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs
src/ReverseProxy/Utilities/ActivityCancellationTokenSource.cs
test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs

Closes #2631
Same idea as #2503, but for `ResponseBodyCanceled` and `UpgradeResponseCanceled`.
`UpgradeResponseCanceled` could be an indication that the backend became unresponsive, but it's ultimately triggered by the client disconnecting. If this is a concern, the activity timeout should be lowered enough to catch such cases instead.

Move ResponseBodyCanceled and UpgradeResponseCanceled to debug-level log event

---

src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs

Adds a workaround to make .NET 8 work.
Closes #2598

Make NativeAOT work on .NET 8.0

---

src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/testassets/multiple-endpoints-same-port/clusters.json
test/Kubernetes.Tests/testassets/multiple-endpoints-same-port/ingress.yaml
test/Kubernetes.Tests/testassets/multiple-endpoints-same-port/routes.json

Kubernetes allow to define multiple times the same port number with different names.
It can cause some duplicate routes to be created.
Fix #2819

[K8s/ingress] Do not duplicate rules when endpoint has multiple ports

---

docs/operations/Branching.md
docs/operations/Release.md
dotnet-yarp-release.yml

This replaces the obsolete "classic" release pipeline with a YAML-based one.
I've done as much validation as possible without actually pushing to NuGet (using the same YAML as in this PR, but with commented-out `nuget push`.

Add a YAML release pipeline

---

docs/designs/config.md

fix a typo `gadeway` => `gateway`

docs: fix a typo

---

src/Kubernetes.Controller/Converters/YarpParser.cs
test/Kubernetes.Tests/IngressConversionTests.cs
test/Kubernetes.Tests/testassets/external-name-ingress/clusters.json
test/Kubernetes.Tests/testassets/https-service-port-protocol/clusters.json
test/Kubernetes.Tests/testassets/https-service-port-protocol/ingress.yaml
test/Kubernetes.Tests/testassets/https-service-port-protocol/routes.json

As of this moment, having multiple entries with different protocols in the same ingress results in failed routing.
Therefore, I would suggest introducing an adjusted service port driven protocol detection.
See how traefik does it for reference: https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#communication-between-traefik-and-pods

Introduce service port driven backend protocol to support different protocols routing in same ingress.
