README.md, docs/operations/StatusReport.md, eng/Generate-StatusReport.ps1
I created a script to pull the last 14 days of external contributions (for using to build a tye-style [status report issue](https://github.com/dotnet/tye/issues/251)). I also linked our status report issue from the README (#97).
I'll post our first update shortly, using this script!
See an example report on #97!
=> Add script to generate status report

samples/ReverseProxy.Sample/Startup.cs, src/ReverseProxy.Core/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
- Put it in the M.E.D namespace
=> Fix the namespace of the AddReverseProxy API

src/ReverseProxy.Core/Service/Proxy/HttpUtilities.cs
- reduce verbosity of HttpUtilities
=> minor clean code

samples/ReverseProxy.Sample/Startup.cs, src/ReverseProxy.Core/Service/Proxy/HttpProxy.cs, test/ReverseProxy.Core.Tests/Service/Proxy/HttpProxyTests.cs
#13 This is a stopgap for preview1 that sets the values without providing any configurability. CopyHeadersToUpstream is the pace I'd expect this transformation to happen long term, but I expect it will be built into a larger request transformation infrastructure such as being discussed in #21.
I changed the Startup sample to reflect that we don't recommend modifying the HttpContext for these kinds of transformations, it would break retries.
=> Basic x-fowarded-* headers

NuGet.config, reverse-proxy.sln, samples/BenchmarkApp/BenchmarkApp.csproj, samples/BenchmarkApp/Program.cs, samples/BenchmarkApp/Properties/launchSettings.json, samples/BenchmarkApp/Startup.cs, samples/BenchmarkApp/appsettings.Development.json, samples/BenchmarkApp/appsettings.json, samples/BenchmarkApp/benchmarks.yml, samples/ReverseProxy.Sample/Properties/launchSettings.json
This is the target of https://github.com/aspnet/Benchmarks/pull/1507/
=> Add sample app for benchmarking

samples/BenchmarkApp/Program.cs
As requested by @sebastienros. 
https://github.com/aspnet/Benchmarks/pull/1517#issuecomment-629568200
=> Output runtime versions during benchmark startup

docs/docfx/articles/getting_started.md, docs/docfx/articles/toc.yml, docs/docfx/articles/tutorial.md, docs/docfx/index.md, docs/docfx/readme.md
Contributes to #172. This is largely the same as the preview1 blog content.
I can't tell if I've broken the links. The local build output does not quite match the CI build output.
=> Getting started doc content

azure-pipelines.yml
Using a custom name will allow to identify the real source of the issues that are filed
=> Fix TSA name

samples/BenchmarkApp/benchmarks.yml
It's part of the bombardier client now
=> Removing warmup job

docs/docfx/articles/runtimes.md, docs/docfx/articles/toc.yml
#172 Starting this page to track what is and isn't supported across runtime versions.
=> Document supported runtimes

src/ReverseProxy/Service/Config/ConfigErrors.cs, src/ReverseProxy/Service/Config/RuleParsing/RouteValidator.cs, src/ReverseProxy/Service/DynamicEndpoints/RuntimeRouteBuilder.cs, test/ReverseProxy.Tests/Service/Config/RuleParsing/RouteValidatorTests.cs
=> Making hostname optional if request path is specified for the route

src/ReverseProxy/Microsoft.ReverseProxy.csproj
This PR adds NuGet package description.
Fixes #194
=> NuGet package description added

docs/docfx/articles/session-affinity.md, src/ReverseProxy/Abstractions/BackendDiscovery/Contract/SessionAffinityOptions.cs, src/ReverseProxy/Middleware/AffinitizedDestinationLookupMiddleware.cs, src/ReverseProxy/Service/Config/DynamicConfigBuilder.cs, src/ReverseProxy/Service/Management/ReverseProxyConfigManager.cs, src/ReverseProxy/Service/RuntimeModel/BackendConfig.cs, test/ReverseProxy.Tests/Middleware/AffinityMiddlewareTestBase.cs, test/ReverseProxy.Tests/Service/SessionAffinity/BaseSesstionAffinityProviderTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/240
=> Rename AffinityFailurePolicy to FailurePolicy

eng/Versions.props
We've branched for preview2, switching master to preview3.
@davidfowl PRs are fine after this.
=> Change the branding to preview.3

docs/docfx/articles/getting_started.md, docs/docfx/articles/runtimes.md
- Getting started
- Supported runtimes
I don't plan to merge until we have the package available on nuget.
=> Update docs for preview2

samples/ReverseProxy.Sample/appsettings.json
fix 'Endpoint' -> 'Destination' in config
fix 'cluster1' -> 'cluster2' in config
Paired with : @masenol
=> Make small fixes to configuration

docs/docfx/articles/cors.md, docs/docfx/articles/toc.yml, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/CorsConstants.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs, src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs, src/ReverseProxy/Service/Config/ConfigErrors.cs, src/ReverseProxy/Service/Config/DynamicConfigBuilder.cs, src/ReverseProxy/Service/Config/RuleParsing/RouteValidator.cs, src/ReverseProxy/Service/ConfigModel/ParsedRoute.cs, src/ReverseProxy/Service/DynamicEndpoints/RuntimeRouteBuilder.cs, test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs, test/ReverseProxy.Tests/Service/Config/RuleParsing/RouteValidatorTests.cs, test/ReverseProxy.Tests/Service/DynamicEndpoints/RuntimeRouteBuilderTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/285
=> Enable cors for for proxy routes

src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs, src/ReverseProxy/Service/HealthProbe/ClusterProber.cs, src/ReverseProxy/Service/Management/ReverseProxyConfigManager.cs, src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs, src/ReverseProxy/Service/RuntimeModel/DestinationInfo.cs, src/ReverseProxy/Signals/IReadableSignal.cs, src/ReverseProxy/Signals/ISignal.cs, src/ReverseProxy/Signals/ISignalSnapshot.cs, src/ReverseProxy/Signals/IWritableSignal.cs, src/ReverseProxy/Signals/Signal.cs, src/ReverseProxy/Signals/SignalContext.cs, src/ReverseProxy/Signals/SignalExtensions.cs, src/ReverseProxy/Signals/SignalFactory.cs, src/ReverseProxy/Signals/Unit.cs, test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/HealthProbe/ClusterProberTests.cs, test/ReverseProxy.Tests/Service/HealthProbe/HealthProbeWorkerTests.cs, test/ReverseProxy.Tests/Service/Management/ReverseProxyConfigManagerTests.cs, test/ReverseProxy.Tests/Service/RuntimeModel/ClusterInfoTests.cs
Design review: This is not an abstraction we want to directly expose to developers. In most cases they should only need access to the state snapshots.
=> Make signals internal

src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs, src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/SessionAffinityOptions.cs, src/ReverseProxy/Abstractions/DestinationDiscovery/Contract/Destination.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs, src/ReverseProxy/Configuration/ProxyConfigOptions.cs, src/ReverseProxy/Service/Config/DynamicConfigBuilder.cs, src/ReverseProxy/Service/ConfigRepos/InMemoryClustersRepo.cs, src/ReverseProxy/Service/Management/ItemManagerBase.cs, src/ReverseProxy/Service/Management/ReverseProxyConfigManager.cs, src/ReverseProxy/Service/SessionAffinity/SessionAffinityMiddlewareHelper.cs, test/ReverseProxy.Tests/Service/Management/ItemManagerBaseTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/209
=> Use OrdinalIgnoreCase for StringComparer

src/ReverseProxy/Service/Config/ProxyRouteTransformExtensions.cs, src/ReverseProxy/Service/Config/TransformBuilder.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/PathRouteValuesTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/PathStringTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderForwardedTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderValueTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedForTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedHostTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPathBaseTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedProtoTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseHeaderValueTransform.cs, test/ReverseProxy.Tests/Common/TestRandom.cs, test/ReverseProxy.Tests/Common/TestRandomFactory.cs, test/ReverseProxy.Tests/Service/Config/ProxyRouteTransformExtensionsTests.cs, test/ReverseProxy.Tests/Service/Proxy/LoadBalancerTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/317
=> Add Helper methods for Transforms

azure-pipelines.yml
This is causing build errors on the CI
=> Remove unix publish

docs/docfx/articles/getting_started.md, eng/Versions.props
We have a build candidate for release so I've updating the branding and docs.
=> Rev docs and versions for preivew 3 release

docs/docfx/articles/runtimes.md
Generalizing this doc so we don't have to update it every preview.
=> Generalize the runtimes doc

samples/ReverseProxy.Code.Sample/CustomConfigFilter.cs, samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs, src/ReverseProxy/Service/Config/RuntimeRouteBuilder.cs, src/ReverseProxy/Service/Management/ProxyConfigManager.cs, src/ReverseProxy/Service/RuntimeModel/RouteConfig.cs, test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs, test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/Config/RuntimeRouteBuilderTests.cs, test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/358
=> Add order to RouteEndpoint

eng/Versions.props
#374 Setting up master for the next milestone
=> Rev the package version to preview.5

docs/operations/Branching.md, docs/operations/Release.md
Adding more detail and updating them to match our current workflow.
=> Update the branching and release docs

docs/docfx/articles/configfiles.md, docs/docfx/articles/configproviders.md, docs/docfx/articles/getting_started.md
#374
- Bump the version numbers
- Simplify getting started and reference our new docs for code base or file based config.
- Simplify some of the samples and make them easier to copy-paste
=> Update getting started for preview 4

.github/workflows/docfx_build.yml, docs/docfx/articles/configfiles.md, docs/docfx/articles/configproviders.md, docs/docfx/articles/getting_started.md, docs/docfx/readme.md
Merging in preview4 docs changes to master. Do not squash.
=> Merge Release/1.0.0 preview4 to master

docs/docfx/articles/proxyhttpclientconfig.md, samples/ReverseProxy.Code.Sample/CustomConfigFilter.cs, samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs, src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs, src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs, src/ReverseProxy/Service/Management/ProxyConfigManager.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs, test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
Removed '*Options' suffixes 
Fixes #396
Please review
Thank you in advance
=> Removed '*Options' suffixes from 'Abstractions.Cluster' properties

docs/docfx/_site/articles/getting_started.html, docs/docfx/articles/getting_started.md
Is there anything else that should be updated for preview 4 => 5? @Tratcher
=> Update getting started for preview5

docs/docfx/articles/getting_started.md
=> Change pragmatically to programatically

src/ReverseProxy/Abstractions/RouteDiscovery/Contract/RouteHeader.cs
=> Fix header comparison typo

src/ReverseProxy/Service/Proxy/HttpProxy.cs, src/ReverseProxy/Service/Proxy/RequestProxyOptions.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestParametersTransformContext.cs, test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs, test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs
=> HTTP Version Policy

docs/operations/Release.md
Shuffled the sections a bit so that it makes more sense IMO.
Filled in little details encountered while doing the release.
=> Update of releasing steps 

src/ReverseProxy/Utilities/CaseSensitiveEqualHelper.cs
Randomly saw this while browsing through code, not related to any PR
=> Fix CaseSensitiveEqualHelper null check

src/ReverseProxy/Service/RuntimeModel/ClusterProxyHttpRequestOptions.cs
https://github.com/microsoft/reverse-proxy/pull/512#discussion_r520729621
=> #512 Follow-up

test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ActiveHealthCheckOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/CircuitBreakerOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterPartitioningOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ProxyHttpRequestOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/QuotaOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/SessionAffinityOptionsTests.cs, test/ReverseProxy.Tests/Abstractions/DestinationDiscovery/Contract/DestinationTests.cs, test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/Management/ClusterManagerTests.cs, test/ReverseProxy.Tests/Service/Management/DestinationManagerFactoryTests.cs, test/ReverseProxy.Tests/Service/Management/DestinationManagerTests.cs, test/ReverseProxy.Tests/Service/Management/ItemManagerBaseTests.cs, test/ReverseProxy.Tests/Service/Management/RouteManagerTests.cs, test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs, test/ReverseProxy.Tests/Service/Proxy/StreamCopyHttpContentTests.cs, test/ReverseProxy.Tests/Service/RuntimeModel/DestinationInfoTests.cs, test/ReverseProxy.Tests/Utilities/AtomicCounterTests.cs, test/ReverseProxy.Tests/Utilities/CaseInsensitiveEqualHelperTests.cs, test/ReverseProxy.Tests/Utilities/ReferenceEqualityComparerTests.cs
Removed the Arrange/Act/Assert test comments
Fixes #527
Please review
Thank you in advance
=> Remove the Arrange/Act/Assert test comments

global.json
Shifting to the stable, released SDK version.
=> Update to 5.0 RTM SDK

src/ReverseProxy/Utilities/ConfigurationReadingExtensions.cs, test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Utilities/ConfigurationReadingExtensionsTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/565
=> Support negative number in config

src/ReverseProxy/Service/Proxy/HttpProxy.cs, test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs
Problem: HttpClient always adds `Transfer-Encoding: chunked` to outgoing HTTP/1.1 requests if the HttpRequestMessage has an HttpContent, even if it's empty. Some servers won't accept requests like GETs that have a `Transfer-Encoding: chunked` header, so YARP has to avoid creating an HttpContent when it doesn't need one.
There are some ambiguous cases where we can't tell if the request has a body by just looking at headers, such as HTTP/2 where Transfer-Encoding is obsolete. Today we mitigate this with a series of heuristics about methods, versions, headers, etc., but it's not foolproof, only the underlying server knows for sure.
This PR consumes the new .NET 5 IHttpRequestBodyDetectionFeature that can be used in pace of any heuristics to check if the server is expecting a request body. …
=> Consume IHttpRequestBodyDetectionFeature

src/ReverseProxy.ServiceFabric/EventIds.cs, src/ReverseProxy.ServiceFabric/FabricWrapper/QueryClientWrapper.cs, src/ReverseProxy.ServiceFabric/ServiceDiscovery/Discoverer.cs, src/ReverseProxy.ServiceFabric/ServiceDiscovery/ServiceExtensionLabelsProvider.cs, src/ReverseProxy.ServiceFabric/ServiceDiscovery/ServiceFabricConfigProvider.cs, src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/CachedServiceFabricCaller.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/559
=> Add log events in Service Fabric project

docs/docfx/articles/proxyhttpclientconfig.md
fix: DangerousAcceptAnyServerCertificate instead of ValidateRemoteCertificate.
=> Update proxyhttpclientconfig.md (#626)

docs/docfx/articles/service-fabric-int.md, samples/ReverseProxy.ServiceFabric.Sample/Startup.cs, src/ReverseProxy.ServiceFabric/Configuration/ServiceFabricServiceCollectionExtensions.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/555
=> Add options parameter for LoadFromServiceFabric

docs/docfx/articles/authn-authz.md, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/AuthorizationConstants.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs, src/ReverseProxy/Service/Config/ConfigValidator.cs, src/ReverseProxy/Service/DynamicEndpoint/ProxyEndpointFactory.cs, test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactorTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/622
=> Support Anonymous in ProxyRoute.AuthorizationPolicy

docs/docfx/articles/service-fabric-int.md
Fixes https://github.com/microsoft/reverse-proxy/issues/588
=> Change Host to Hosts in doc

docs/docfx/articles/direct-proxying.md, samples/ReverseProxy.Direct.Sample/Startup.cs
These are doc updates to go with the recent transforms changes in IHttpProxy (#612).
=> Update direct proxy docs for transforms

src/ReverseProxy/Service/Proxy/StreamCopier.cs
System.IO.Pipelines has been investigated in https://github.com/microsoft/reverse-proxy/pull/330.
=> Remove Pipelines TODO comment

docs/docfx/articles/toc.yml
Same as #669, but for the release branch
=> Add load balancing docs to TOC

docs/docfx/articles/service-fabric-int.md, src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs, test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/589
=> TimeSpans in Service Fabric config

azure-pipelines.yml
https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#2-add-main-triggers-to-yaml-pipelines
=> Add main branch as pipeline trigger

azure-pipelines.yml, docs/README.md, docs/docfx/readme.md, docs/operations/Branching.md, docs/operations/Release.md, src/ReverseProxy/Service/Management/ProxyConfigManager.cs
https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#6-search-your-repository-for-any-references-to-the-main-branch-specific-to-your-repo
https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#11-remove-the-master-branch-triggers-from-your-yaml-pipelines
=> Replace relevant occurrences of master to main.

docs/docfx/articles/transforms.md, samples/ReverseProxy.Code.Sample/MyTransformFactory.cs, samples/ReverseProxy.Code.Sample/MyTransformProvider.cs, src/ReverseProxy/Abstractions/Config/TransformBuilderContextFuncExtensions.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/HttpMethodChangeTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/PathRouteValuesTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/PathStringTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/QueryParameterRemoveTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/QueryParameterTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestCopyHostTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestFuncTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderClientCertTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderForwardedTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderValueTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedForTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedHostTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPathBaseTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedProtoTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseFuncTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseHeaderValueTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTrailerValueTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTrailersFuncTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTrailersTransform.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseTransform.cs, test/ReverseProxy.Tests/Abstractions/Config/TransformBuilderContextFuncExtensionsTests.cs, test/ReverseProxy.Tests/Service/Config/TransformBuilderTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/685
=> Use ValueTask in transforms

src/ReverseProxy/Utilities/RequestUtilities.cs
`StringBuilder` => `string.Concat`
=> Reduce allocations in MakeDestinationAddress

src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs, src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs, src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs, test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Service/Proxy/Infrastructure/ProxyHttpClientFactoryTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/675
=> Add EnableMultipleHttp2Connections to ProxyHttpClientOptions

eng/Versions.props
=> Update for preview.10

docs/docfx/articles/getting_started.md
PR for visibility, but I'll auto-merge.
=> Update Getting Started for preview 9

docs/operations/Branching.md, docs/operations/Release.md, global.json
Updating our local runtime and SDKs to the latest patch version, and updating the instructions to do this after every release.
=> Update global.json and instructions.

docs/docfx/articles/transforms.md, src/ReverseProxy/Service/RuntimeModel/Transforms/NodeFormat.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderForwardedTransform.cs, test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/RequestHeaderForwardedTransformTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/763
=> Support obfuscated port in forwarded transform

src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs, src/ReverseProxy/Service/Config/ConfigValidator.cs, src/ReverseProxy/Service/HealthChecks/ActiveHealthCheckMonitor.cs, src/ReverseProxy/Utilities/ServiceLookupHelper.cs, test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/782
=> Set default policy for passive and active health check

src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs, test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
Follows https://github.com/microsoft/reverse-proxy/pull/760
=> Support RequestHeaderEncoding in ServiceFabric

reverse-proxy.sln, testassets/ReverseProxy.Direct/Program.cs, testassets/ReverseProxy.Direct/Properties/launchSettings.json, testassets/ReverseProxy.Direct/ReverseProxy.Direct.csproj, testassets/ReverseProxy.Direct/Startup.cs, testassets/ReverseProxy.Direct/appsettings.Development.json, testassets/ReverseProxy.Direct/appsettings.json
I've made a copy of the Direct.Sample project under testassets for use when prototyping and debugging.
=> Copy the Direct sample for development

src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs, src/ReverseProxy/Service/HealthChecks/DefaultProbingRequestFactory.cs, src/ReverseProxy/Service/Management/ProxyConfigManager.cs, src/ReverseProxy/Service/RuntimeModel/DestinationConfig.cs, test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/HealthChecks/ActiveHealthCheckMonitorTests.cs, test/ReverseProxy.Tests/Service/HealthChecks/ConsecutiveFailuresHealthPolicyTests.cs, test/ReverseProxy.Tests/Service/HealthChecks/DefaultProbingRequestFactoryTests.cs, test/ReverseProxy.Tests/Service/HealthChecks/TransportFailureRateHealthPolicyTests.cs, test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/788
=> Store instance of Destination in DestinationConfig

src/ReverseProxy/Service/Management/ProxyConfigManager.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/798
=> Use List instead of SortedList in VerifyRoutesAsync

reverse-proxy.sln, samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj, samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj, src/ReverseProxy.ServiceFabric/Yarp.ReverseProxy.ServiceFabric.csproj, src/ReverseProxy.TelemetryConsumption/Yarp.ReverseProxy.Telemetry.Consumption.csproj, src/ReverseProxy/Yarp.ReverseProxy.csproj, test/ReverseProxy.FunctionalTests/Yarp.ReverseProxy.FunctionalTests.csproj, test/ReverseProxy.ServiceFabric.Tests/Yarp.ReverseProxy.ServiceFabric.Tests.csproj, test/ReverseProxy.Tests.Common/Yarp.ReverseProxy.Tests.Common.csproj, test/ReverseProxy.Tests/Yarp.ReverseProxy.Tests.csproj, testassets/BenchmarkApp/BenchmarkApp.csproj, testassets/ReverseProxy.Code/ReverseProxy.Code.csproj, testassets/ReverseProxy.Config/ReverseProxy.Config.csproj, testassets/ReverseProxy.Direct/ReverseProxy.Direct.csproj
Contributes to #811. I'm starting with just the projects/packages to see if anything in the CI infrastructure breaks. We'll get to namespace churn in the next PR.
=> Rebrand packages/projects 

eng/Versions.props
=> Update Version to preview.11

global.json
=> Update SDK versions in global.json

docs/docfx/articles/getting_started.md
=> Update Getting Started for preview 10

docs/docfx/articles/configproviders.md, docs/docfx/articles/getting_started.md, docs/docfx/index.md
=> Merge release/docs into main

src/ReverseProxy/Configuration/ReverseProxyIEndpointRouteBuilderExtensions.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/860
=> Return ReverseProxyConventionBuilder in MapReverseProxy

src/ReverseProxy/Service/Management/EntityActionScheduler.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/742
=> Dispose the timer

src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderForwardedTransform.cs, src/ReverseProxy/Utilities/ValueStringBuilder.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/799
=> Use ValueStringBuilder for forwarded transform

docs/docfx/articles/transforms.md, src/ReverseProxy/Abstractions/Config/ForwardedTransformExtensions.cs, src/ReverseProxy/Service/Config/ForwardedTransformFactory.cs, src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPrefixTransform.cs, test/ReverseProxy.Tests/Abstractions/Config/ForwardedTransformExtensionsTests.cs, test/ReverseProxy.Tests/Service/Config/TransformBuilderTests.cs, test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPrefixTransformTests.cs, testassets/ReverseProxy.Config/appsettings.json
Fixes https://github.com/microsoft/reverse-proxy/issues/737
=> Rename X-Fowarded-PathBase to X-Forwarded-Prefix

docs/docfx/articles/authn-authz.md, docs/docfx/articles/configfiles.md, docs/docfx/articles/configproviders.md, docs/docfx/articles/cors.md, docs/docfx/articles/getting_started.md, docs/docfx/articles/header-routing.md, docs/docfx/articles/transforms.md, samples/BasicYarpSample/BasicYarpSample.csproj, samples/BasicYarpSample/appsettings.json, samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj, samples/ReverseProxy.Auth.Sample/appsettings.json, samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj, samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj, samples/ReverseProxy.Config.Sample/appsettings.json, samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj, samples/ReverseProxy.ConfigFilter.Sample/appsettings.json, samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj, samples/ReverseProxy.Direct.Sample/Startup.cs, samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj, samples/ReverseProxy.Metrics.Sample/appsettings.json, samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj, samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj, samples/ReverseProxy.Transforms.Sample/appsettings.json, src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs, test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs, testassets/BenchmarkApp/Startup.cs, testassets/ReverseProxy.Config/appsettings.json
Fixes https://github.com/microsoft/reverse-proxy/issues/279
=> Change routes from array to object

src/ReverseProxy/Service/Config/ConfigValidator.cs, test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/634
=> Raise error when a keyword is used for policy

src/ReverseProxy.Kubernetes.Controller/Converters/YarpParser.cs, src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs, src/ReverseProxy/Abstractions/RouteDiscovery/Contract/RouteMatch.cs, src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs, src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs, src/ReverseProxy/Middleware/HttpContextFeaturesExtensions.cs, src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs, src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs, src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs, src/ReverseProxy/Middleware/SessionAffinityMiddleware.cs, src/ReverseProxy/Service/LoadBalancing/RoundRobinLoadBalancingPolicy.cs, src/ReverseProxy/Service/SessionAffinity/AffinitizeTransform.cs, test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs, test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs, test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyMatchTests.cs, test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs, test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/IntegrationTests/RoutingTests.cs, test/ReverseProxy.Tests/Middleware/PassiveHealthCheckMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Middleware/ProxyPipelineInitializerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs, test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactoryTests.cs, test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs, testassets/ReverseProxy.Code/Startup.cs, testassets/ReverseProxy.Config/Startup.cs
ProxyMatch -> RouteMatch
AddProxyConfigFilter -> AddConfigFilter
ConfigureClient -> ConfigureHttpClient
=> API renames: ProxyMatch, AddProxyConfigFilter, ConfigureClient

src/OperatorFramework/src/Controller/Microsoft.Kubernetes.Controller.csproj, src/OperatorFramework/src/Core/Microsoft.Kubernetes.Core.csproj, src/OperatorFramework/src/CustomResource/Microsoft.Kubernetes.CustomResources.csproj, src/OperatorFramework/src/Operator/Microsoft.Kubernetes.Operator.csproj, src/OperatorFramework/src/ResourceKinds.OpenApi/Microsoft.Kubernetes.ResourceKinds.OpenApi.csproj, src/OperatorFramework/src/Testing/Microsoft.Kubernetes.Testing.csproj, src/ReverseProxy.Kubernetes.Controller/Yarp.ReverseProxy.Kubernetes.Controller.csproj, src/ReverseProxy.Kubernetes.Ingress/Yarp.ReverseProxy.Kubernetes.Ingress.csproj, src/ReverseProxy.Kubernetes.Protocol/Yarp.ReverseProxy.Kubernetes.Protocol.csproj
=> Add IsPackable=false for Kubernetes pacakges on internal builds

samples/README.md
Note: We need to add "Tags" for the latest release and links for those into this doc. I think its as simple as 
```
git tag -m "Marking preview10 as the latest" latest v1.0.0-preview10
git push --tags
```
But we need to confirm, and I don't think that happens as part of a PR.
=> Adding a README for the samples folder

eng/Versions.props, global.json
=> Update preview version and SDK versions

azure-pipelines.yml, eng/PoliCheckExclusions.xml, samples/ReverseProxy.ConfigFilter.Sample/CustomConfigFilter.cs
Moving to [our variable group](https://dev.azure.com/dnceng/internal/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=112&path=YARP-SDLValidation-Params) for SDL parameters and resolving PoliCheck issues.
=> Update SDL config for YARP

eng/sdl-tsa-vars.config
AspNetCore for reference: https://github.com/dotnet/aspnetcore/blob/main/eng/sdl-tsa-vars.config
=> Add sdl-tsa-vars.config

src/ReverseProxy/Utilities/RequestUtilities.cs
Small nit since I missed reviewing #977
=> Use StartsWith

src/ReverseProxy/Service/Proxy/HttpProxy.cs, src/ReverseProxy/Service/Proxy/IHttpProxy.cs, src/ReverseProxy/Service/Proxy/IHttpProxyExtensions.cs, test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs, test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/962
=> ProxyAsync returns ProxyError

src/ReverseProxy/Abstractions/Config/ResponseTransformExtensions.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/987
=> Set default value to success for response headers and trailers transform

reverse-proxy.sln
Currently VS is failing to load the project because of the path mismatch.
=> Fix KubernetesIngress sample backend path in .sln

samples/KuberenetesIngress.Sample/Ingress/Yarp.ReverseProxy.Kubernetes.Ingress.csproj
=> Add 6.0 target to Kubernetes Ingress sample

docs/docfx/articles/load-balancing.md, src/ReverseProxy/Service/LoadBalancing/FirstLoadBalancingPolicy.cs, src/ReverseProxy/Service/LoadBalancing/LoadBalancingPolicies.cs, test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/980
=> Change First load balance policy to alphabetical

reverse-proxy.sln, samples/README.md, samples/ReverseProxy.Minimal.Sample/Program.cs, samples/ReverseProxy.Minimal.Sample/Properties/launchSettings.json, samples/ReverseProxy.Minimal.Sample/README.md, samples/ReverseProxy.Minimal.Sample/ReverseProxy.Minimal.Sample.csproj, samples/ReverseProxy.Minimal.Sample/appsettings.Development.json, samples/ReverseProxy.Minimal.Sample/appsettings.json
Fixes #937
I will add doc updates to this PR, opening as a draft just because I think it's cool we're at < 10 non-empty LOC to have a functioning reverse proxy.
=> Add Minimal sample

test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs, testassets/TestClient/Scenarios/Http2PostExpectContinueScenario.cs
=> Test Expect: 100-continue when body is not sent

docs/docfx/articles/configfiles.md, docs/docfx/articles/configproviders.md
=> Link to ASP.NET Core route template syntax

docs/docfx/articles/packages-refs.md
=> Packages referenced by YARP

azure-pipelines.yml
=> Switch from ubuntu-16.04 to ubuntu-latest

samples/ReverseProxy.Metrics.Sample/ForwarderTelemetryConsumer.cs, samples/ReverseProxy.Metrics.Sample/README.md, testassets/ReverseProxy.Code/ForwarderTelemetryConsumer.cs, testassets/ReverseProxy.Code/Startup.cs
Telemetry consumers have been updated to only be singletons, but I forgot to update the sample in testassets.
=> Update testassets Telemetry consumer & metrics sample readme

docs/docfx/docfx.csproj
=> Update docfx to 2.58

src/ReverseProxy.Kubernetes.Controller/Converters/ClusterTransfer.cs, src/ReverseProxy.Kubernetes.Controller/Converters/YarpIngressContext.cs, src/ReverseProxy.Kubernetes.Controller/Converters/YarpParser.cs
Not crucial but maybe worth to do ;)
=> Rename ClusterTrasfer to ClusterTransfer

src/ReverseProxy/Forwarder/RequestUtilities.cs, test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
Added filtering of headers with new line characters to `RequestUtilities.AddHeader`.
Users can still force such headers be sent in custom transforms by calling `HttpRequestMessage.Headers.TryAddWithoutValidation`.
Fixed the prohibited headers test that was using `Name: Value` instead of `Name` when asserting that headers are present.
=> Remove headers with new line characters

docs/docfx/articles/config-files.md
Cherry-pick the commit to main.
=> Fix small typo in configfiles.md (#1081)

src/ReverseProxy/Transforms/RequestHeadersTransformFactory.cs, test/ReverseProxy.Tests/Transforms/RequestHeadersTransformExtensionsTests.cs
Currently you are unable to use RequestHeaderRemove transformation since the wrong key is used.
=> Use RequestHeaderRemoveKey for transformation

src/ReverseProxy/Health/ActiveHealthCheckMonitor.cs, src/ReverseProxy/Health/EntityActionScheduler.cs, test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs
=> Register cluster for active health check when it's enabled on reload

src/ReverseProxy/Forwarder/RequestUtilities.cs, test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
=> Remove HTTP2-Settings request header

src/ReverseProxy/Forwarder/RequestUtilities.cs, test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs
=> Remove Upgrade-Insecure-Requests header

src/ReverseProxy/Health/EntityActionScheduler.cs
=> Fix race conditions in EntityActionScheduler

samples/ReverseProxy.Direct.Sample/HttpForwarderExtensions.cs, samples/ReverseProxy.Direct.Sample/RequestTransformer.cs, samples/ReverseProxy.Direct.Sample/Startup.cs
Fixes https://github.com/microsoft/reverse-proxy/issues/1172
=> Add request transform extension method

docs/docfx/articles/load-balancing.md
https://github.com/microsoft/reverse-proxy/blob/40ae654f5e778a66b1c06ad4a42e6655b13c10a5/src/ReverseProxy/LoadBalancing/FirstLoadBalancingPolicy.cs#L16
https://github.com/microsoft/reverse-proxy/blob/40ae654f5e778a66b1c06ad4a42e6655b13c10a5/src/ReverseProxy/LoadBalancing/LoadBalancingPolicies.cs#L14
=> Fix the FirstAlphabetical policy name

docs/docfx/articles/config-files.md
=> Change First to FirstAlphabetical in docs

src/ReverseProxy/Forwarder/HttpTransformer.cs, test/ReverseProxy.FunctionalTests/HeaderTests.cs, test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs
Backport of #1220 to preview12 branch.
=> Remove the Content-Length header

docs/docfx/articles/dests-health-checks.md
=> Health probing request customization docs

test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs
=> Tests veryfing skip body request behavior in Expect 100 scenarios

azure-pipelines.yml
Switching to servicing pools per https://github.com/dotnet/core-eng/issues/14276.
=> Switch to 1ES servicing pools on release/1.0.0-preview12

docs/docfx/articles/getting-started.md, samples/ReverseProxy.Minimal.Sample/Program.cs, samples/ReverseProxy.Minimal.Sample/ReverseProxy.Minimal.Sample.csproj
=> Updating getting started to include the minimal sample for .NET 6

src/TelemetryConsumption/NameResolution/NameResolutionEventListenerService.cs, src/TelemetryConsumption/NameResolution/NameResolutionMetrics.cs
=> Add current-dns-lookups NameResolution metric

docs/docfx/articles/transforms.md
=> More client cert docs

docs/docfx/articles/distributed-tracing.md, docs/docfx/articles/toc.yml, samples/ReverseProxy.Code.Sample/DiagnosticsHandlerFactory.cs, samples/ReverseProxy.Code.Sample/Startup.cs
Fixes #708
Should the sample implementation be a separate file in this repo or is a gist okay?
=> Add article on Distributed Tracing

eng/Versions.props
=> Avoid adding the build number to a release package version

eng/Versions.props
=> Bump version to 1.1.0.preview.1

docs/docfx/articles/getting-started.md
I will cherry-pick this back onto main
Contributes to #1353
=> Update getting started for 1.0.0

docs/operations/Branching.md
=> Update Branching doc

samples/ReverseProxy.Config.Sample/appsettings.json
Fixes #1394 by removing outdated config samples for client certs.
=> Remove outdated client cert config

src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj
=> misc: remove unused reference

src/ReverseProxy/Forwarder/HttpTransformer.cs, test/ReverseProxy.Tests/Forwarder/HttpTransformerTests.cs
=> Add test for `HttpTransformer.Empty`

src/Kubernetes.Controller/Converters/YarpParser.cs, test/Kubernetes.Tests/IngressConversionTests.cs, test/Kubernetes.Tests/testassets/basic-ingress/clusters.json, test/Kubernetes.Tests/testassets/basic-ingress/routes.json, test/Kubernetes.Tests/testassets/exact-match/clusters.json, test/Kubernetes.Tests/testassets/exact-match/routes.json, test/Kubernetes.Tests/testassets/hostname-routing/clusters.json, test/Kubernetes.Tests/testassets/hostname-routing/routes.json, test/Kubernetes.Tests/testassets/https/clusters.json, test/Kubernetes.Tests/testassets/https/routes.json, test/Kubernetes.Tests/testassets/mapped-port/clusters.json, test/Kubernetes.Tests/testassets/mapped-port/routes.json, test/Kubernetes.Tests/testassets/multiple-endpoints-ports/clusters.json, test/Kubernetes.Tests/testassets/multiple-endpoints-ports/routes.json, test/Kubernetes.Tests/testassets/multiple-ingresses-one-svc/clusters.json, test/Kubernetes.Tests/testassets/multiple-ingresses-one-svc/routes.json, test/Kubernetes.Tests/testassets/multiple-namespaces/clusters.json, test/Kubernetes.Tests/testassets/multiple-namespaces/ingress.yaml, test/Kubernetes.Tests/testassets/multiple-namespaces/routes.json
=> #1389 Added K8S namespace to cluster and route IDs

README.md
Apparently it is hard to find. #1557
=> Added a link to daily builds

docs/docfx/articles/distributed-tracing.md
=> Point users of custom distributed tracing mechanisms at DistributedContextPropagator

src/Kubernetes.Controller/Services/IngressController.cs
=> Fix typos in IngressController

eng/Versions.props
=> Update PreReleaseVersionLabel to rc.2

docs/docfx/articles/config-files.md
I will backport this change onto release/latest once https://github.com/microsoft/reverse-proxy/issues/1596 is finished as well.
=> Add language and fix indentation for configuration code sample

docs/docfx/articles/transforms.md
=> Docs for custom request and response body transforms 

docs/docfx/articles/http-client-config.md, docs/docfx/articles/http3.md, docs/docfx/articles/toc.yml, src/ReverseProxy/Configuration/ConfigValidator.cs, src/ReverseProxy/Forwarder/HttpForwarder.cs, src/ReverseProxy/Utilities/EventIds.cs, test/ReverseProxy.Tests/Configuration/ConfigValidatorTests.cs
Resolves #1208 
Mostly docs update and adding new version into config validation.
=> Add HTTP/3 support

docs/docfx/articles/config-files.md, docs/docfx/articles/config-filters.md, docs/docfx/articles/config-providers.md, docs/docfx/articles/toc.yml
=> Docs for IProxyConfigFilter 

docs/docfx/articles/httpsys-delegation.md, src/ReverseProxy/Delegation/DelegationExtensions.cs, src/ReverseProxy/Delegation/HttpSysDelegator.cs, src/ReverseProxy/Delegation/IHttpSysDelegator.cs, src/ReverseProxy/Management/IReverseProxyBuilderExtensions.cs, src/ReverseProxy/Utilities/EventIds.cs, test/ReverseProxy.FunctionalTests/HttpSysDelegationTests.cs, test/ReverseProxy.Tests/Delegation/HttpSysDelegatorTests.cs
=> Adding support to reset http.sys delegation queues

docs/docfx/articles/header-guidelines.md, src/ReverseProxy/Configuration/ConfigValidator.cs, src/ReverseProxy/Utilities/EventIds.cs
=> Correct documentation

src/OperatorFramework/src/Core/Microsoft.Kubernetes.Core.csproj, src/OperatorFramework/src/CustomResource/Microsoft.Kubernetes.CustomResources.csproj, src/OperatorFramework/src/Testing/Microsoft.Kubernetes.Testing.csproj
=> Update KubernetesClient to 6.0.25

docs/docfx/articles/http-client-config.md
=> Docs for WebProxy 

docs/docfx/articles/header-routing.md
=> Update header-routing docs after #1639

docs/docfx/articles/lets-encrypt.md
=> Fix LettuceEncrypt url (#1686)

samples/README.md
bug fix the table navigation link to the k8s sample
=> patch (samples table): fix k8s ref sample

samples/BasicYarpSample/BasicYarpSample.csproj, samples/Prometheus/ReverseProxy.Metrics-Prometheus.Sample/ReverseProxy.Metrics.Prometheus.Sample.csproj, samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj, samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj, samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj, samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj, samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj, samples/ReverseProxy.LetsEncrypt.Sample/ReverseProxy.LetsEncrypt.Sample.csproj, samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj, samples/ReverseProxy.Minimal.Sample/ReverseProxy.Minimal.Sample.csproj, samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj
Fixes #1676
This is a routine witch over to package references to make the release branch samples easier to copy paste.
=> Change project to package references in release branch #1676

src/Kubernetes.Controller/Protocol/Receiver.cs, src/Kubernetes.Controller/Services/Reconciler.cs
=> Better error logging

src/Kubernetes.Controller/Services/IngressController.cs, test/Kubernetes.Tests/Client/SyncResourceInformer.cs, test/Kubernetes.Tests/IngressControllerTests.cs, test/Kubernetes.Tests/IngressConversionTests.cs, test/Kubernetes.Tests/Yarp.Kubernetes.Tests.csproj
See WorkQueueTests tests for a reference. Partially fixes #1736.
=> Fix reconciler stops running on an exception

src/Kubernetes.Controller/Services/Reconciler.cs, test/Kubernetes.Tests/IngressCacheTests.cs, test/Kubernetes.Tests/IngressControllerTests.cs, test/Kubernetes.Tests/ReconcilerTests.cs, test/Kubernetes.Tests/Utils/TestLogger.cs
=> Reconciler proceeds with other ingresses after poison pill ingress

eng/Versions.props
=> Update version to 1.1.1-preview.1

eng/Versions.props
=> Update version to 1.1.1 rtw

.github/workflows/docker_build.yml, samples/KubernetesIngress.Sample/backend/Dockerfile
Matches the other dockerfiles now that these projects also target 7.0
=> Use 7.0 SDK in the backend dockerfile

docs/docfx/articles/transforms.md
Same as #1818 but for release/latest.
=> Update AddOriginalHost transform docs

src/ReverseProxy/Management/ProxyConfigManager.cs, test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs
=> Throw on duplicate Route IDs

global.json
@Kahbazi this should unblock working on the rate limiting feature https://github.com/microsoft/reverse-proxy/issues/1776
=> Update the sdk and runtimes to 7.0 rc.2 and 6.0.8

.config/CredScanSuppressions.json
This isn't needed anymore after #994
=> Remove outdated CredScan suppression

docs/docfx/docfx.csproj
=> Bump Docfx to 2.59.4

docs/docfx/articles/getting-started.md
Removes invalid comma in JSON configuration after ReverseProxy.Routes.route1.Match.
=> Fixes typo in getting-started.md

eng/Version.Details.xml, eng/Versions.props, test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs, test/ReverseProxy.FunctionalTests/HttpForwarderCancellationTests.cs, test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs, test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs, test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs, test/ReverseProxy.FunctionalTests/Yarp.ReverseProxy.FunctionalTests.csproj
Fix https://github.com/microsoft/reverse-proxy/issues/1840
=> Treat FunctionalTests project as tests

docs/docfx/articles/direct-forwarding.md, samples/ReverseProxy.Direct.Sample/Startup.cs, src/ReverseProxy/Forwarder/DirectForwardingHttpClientProvider.cs, src/ReverseProxy/Management/ReverseProxyServiceCollectionExtensions.cs, src/ReverseProxy/Routing/DirectForwardingIEndpointRouteBuilderExtensions.cs, testassets/ReverseProxy.Direct/Startup.cs
=> Add extension methods for adding direct forwarding to the ASP.NET Core request pipeline (#1972)

test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs
I can't see this failing locally, but what I imagine is happening is that:
- The client sends the close message and closes the connection in close succession
- The proxy is reading from the client and receives the close message and the connection close at about the same time
- Kestrel signals `RequestAborted` in response to the connection close
- The proxy happens to observe the cancellation before reading the close message and tears everything down (this is a race - that's why the test is flaky)
- Because the close message never went through the request pipeline, the telemetry parser never saw it, so we don't consider the close as graceful
=> Fix ConnectionClosed_BlameAttributedCorrectly test

src/ReverseProxy/Health/DestinationHealthUpdater.cs
=> Change UnhealthyDestinationIsScheduledForReactivation LogLevel to Warning

test/ReverseProxy.FunctionalTests/TelemetryConsumptionTests.cs
Closes #1881
Trying to see if it'll fail in CI
=> Re-enable TelemetryConsumptionWorks test

eng/Versions.props
=> Bump version to RC 1 in prep for release

src/ReverseProxy/Configuration/HeaderMatchMode.cs
These comments are no longer correct after #1639
=> Update triple slash comments on HeaderMatchMode

docs/docfx/api/index.md, docs/docfx/articles/index.md, docs/docfx/index.md, docs/docfx/toc.yml
Closes #1998
Contributes to #1995
=> Link to 1.1 docs from 2.0 docs

src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj
=> Set IsPackable to false for the k8s project (#2005)

docs/docfx/articles/getting-started.md, samples/BasicYarpSample/BasicYarpSample.csproj, samples/Prometheus/ReverseProxy.Metrics-Prometheus.Sample/ReverseProxy.Metrics.Prometheus.Sample.csproj, samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj, samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj, samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj, samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj, samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj, samples/ReverseProxy.HttpSysDelegation.Sample/ReverseProxy/ReverseProxy.HttpSysDelegation.Sample.csproj, samples/ReverseProxy.LetsEncrypt.Sample/ReverseProxy.LetsEncrypt.Sample.csproj, samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj, samples/ReverseProxy.Minimal.Sample/ReverseProxy.Minimal.Sample.csproj, samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj
=> Update package versions in samples

docs/docfx/articles/diagnosing-yarp-issues.md
This should fix #676 unless someone has ideas of what else we'd document in YARP.
=> Link to .NET networking telemetry docs

docs/docfx/articles/config-files.md, docs/docfx/articles/header-routing.md
=> [DOCS] Add NotExists for header routing

docs/docfx/articles/http-client-config.md
=> Update http-client-config.md (#2092)

samples/ReverseProxy.Direct.Sample/Startup.cs, src/ReverseProxy/Routing/DirectForwardingIEndpointRouteBuilderExtensions.cs
- Added helpers to make direct routing more easily accessible.
- Updated the sample to use them.
Fixes https://github.com/microsoft/reverse-proxy/issues/2131
=> Added more direct routing APIs

.github/workflows/markdownlint-problem-matcher.json, .github/workflows/markdownlint.yml, .markdownlint.json
this wouldn't have found https://github.com/microsoft/reverse-proxy/pull/2243, but it will at least find broken links within the repo.
=> add markdownlint

eng/Versions.props
#2234 Updating to something recent for validation and in case we release a preview. We'll still need to do a final update to the RTM version.
=> Update TimeProvider to rc1

eng/Versions.props
=> Update dependencies to rtw

src/Kubernetes.Controller/Client/V1IngressResourceStatusUpdater.cs, src/Kubernetes.Controller/Yarp.Kubernetes.Controller.csproj
Update the KubernetesClient Dependency to 10.x
Closes #2336
=> Update the Kubernetes Client to 10.x

docs/docfx/articles/ab-testing.md
=> Fix sample in ab-testing.md

docs/docfx/articles/distributed-tracing.md
=> Add generic Otel distributed tracing instructions (#2395)

docs/docfx/articles/load-balancing.md
Backport of #2411 to release/latest
=> fix csharp example in load balancing page (#2411)

docs/docfx/articles/direct-forwarding.md
=> Update direct-forwarding.md (#2431)

.github/workflows/docfx_build.yml
Backport of #2409 to main
Worked on release/latest, the website is getting updated again now.
=> Add 'contents: write' permissions to docfx build GitHub Action (#2409)

docs/docfx/articles/toc.yml
Same as #2437 but for release/latest
=> Add query parameter routing to TOC

docs/docfx/articles/direct-forwarding.md, docs/docfx/articles/http-client-config.md, samples/ReverseProxy.Direct.Sample/Program.cs, src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs, testassets/ReverseProxy.Direct/Program.cs
Backport of #2451 to release/latest
=> Use consistent handler defaults in docs and samples

docs/roadmap.md
Add supported and end-of-life releases list
=> Add releases to Roadmap

azure-pipelines.yml
Diffs without whitespace changes: https://github.com/microsoft/reverse-proxy/pull/2464/files?diff=split&w=1
=> Remove CodeQL scheduled runs

azure-pipelines.yml
Backport of #2464 to release/2.0
=> [release/2.0] Remove CodeQL scheduled runs

.github/CODEOWNERS, azure-pipelines.yml
=> [release/2.1] Stop using -pt images

eng/Versions.props
=> Update version label to preview 2

docs/operations/Release.md
=> Update source code archival link

docs/roadmap.md
Backport of #2594 to release/latest
=> [release/latest] Update supported versions table

test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs, test/ReverseProxy.Tests/Transforms/RequestHeadersTransformExtensionsTests.cs
Unblocks #2634 and #2635 that include a new analyzer warning for this case
=> Use the correct Assert.Single overload

test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs, test/ReverseProxy.Tests/Transforms/RequestHeadersTransformExtensionsTests.cs
Backport of #2637 to release/2.1
cc: @MihaZupan
=> [release/2.1] Use the correct Assert.Single overload

test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs, test/ReverseProxy.Tests/Management/ProxyConfigManagerTests.cs, test/ReverseProxy.Tests/Transforms/RequestHeadersTransformExtensionsTests.cs
Backport of #2637 to release/2.2
cc: @MihaZupan
=> [release/2.2] Use the correct Assert.Single overload

.config/tsaoptions.json, azure-pipelines.yml
This gets the results to flow back to https://tsaapivnext.azurewebsites.net/Result/CodeBase/ReverseProxy/Summary (internal only).
=> Fix SDL config

azure-pipelines.yml
Followup after #2833
Passed an internal build here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2708473&view=results
=> Enable binskim

eng/yarpapppack/Common.projitems
Fix https://github.com/dotnet/yarp/issues/2909
CC @lbussell
=> Compute sha512 for the zip container app files

eng/Publishing.props, src/Application/Yarp.Application.csproj
=> Publish tar.gz and sha512 in Publishing.props

azure-pipelines-nonprod.yml
The diff between the two is just official => unofficial: https://www.diffchecker.com/7doC3Q3q/
=> Add non-prod variant of azure-pipelines.yml
